### ISSUE TITLE
Variable product quantity show only 1 in order details

### ISSUE THREAD

**Issue by adinighter** [woocommerce/woocommerce-android#3811] opened 2021-04-06 12:34 UTC
**Describe the bug**
This bug does not happen all the time, it has happened to me twice so far (within a month).
When a product variation is purchased with an amount of more than 1, in the mobile app only 1 is shown as the quantity.
(as you can see in screenshots).

**Screenshots**
<img src="https://user-images.githubusercontent.com/69730437/113709136-cebdf000-96ea-11eb-8105-f03eca72e5c3.jpg" width="270" alt="k_mob">

<img src="https://user-images.githubusercontent.com/69730437/113709139-cfef1d00-96ea-11eb-972a-70f90b27584e.jpg" alt="k_desk">

**Expected behavior**
show the right quantity of the item that has been purchased.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Oneplus 6T, Samsung galaxy 9
- Android version: 10
- WooCommerce Android version: 6.2, 6.3

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): ***
Site address (URL): ***
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: he_IL
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.16
PHP Post Max Size: 2 GB
PHP Time Limit: 3600
PHP Max Input Vars: 9000
cURL Version: 7.75.0
OpenSSL/1.1.1g-fips

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.18-MariaDB
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wp_
Total Database Size: 142.44MB
Database Data Size: 98.99MB
Database Index Size: 43.45MB
wp_woocommerce_sessions: Data: 0.38MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.39MB + Index: 0.22MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 3.52MB + Index: 4.55MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 5.02MB + Index: 1.33MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.34MB + Index: 1.89MB + Engine InnoDB
wp_alm: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_db7_forms: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_crawler: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_crawler_blacklist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_cssjs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_options: Data: 26.08MB + Index: 4.13MB + Engine InnoDB
wp_postmeta: Data: 34.45MB + Index: 15.69MB + Engine InnoDB
wp_posts: Data: 9.34MB + Index: 4.73MB + Engine InnoDB
wp_redirects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.42MB + Index: 0.47MB + Engine InnoDB
wp_terms: Data: 0.23MB + Index: 0.23MB + Engine InnoDB
wp_term_relationships: Data: 1.44MB + Index: 0.39MB + Engine InnoDB
wp_term_taxonomy: Data: 0.33MB + Index: 0.41MB + Engine InnoDB
wp_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.39MB + Index: 0.64MB + Engine InnoDB
wp_wc_order_stats: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.45MB + Index: 0.73MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 9.52MB + Index: 5.23MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.44MB + Index: 0.47MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.19MB + Index: 0.19MB + Engine InnoDB
wp_yoast_seo_links: Data: 1.44MB + Index: 0.48MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.11MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 19
acf-field-group: 7
attachment: 9152
dt_gallery: 24
dt_logos: 10
dt_slideshow: 3
dt_testimonials: 12
nav_menu_item: 166
oembed_cache: 9
page: 25
post: 160
product: 2259
product_variation: 3937
revision: 37
shop_order: 761
vc_grid_item: 5
vc_settings_preset: 1
wpcf7_contact_form: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

The7 Ultimate Addons for WPBakery Page Builder: by Brainstorm Force – 3.19.9
Advanced Custom Fields: by Elliot Condon – 5.9.5
FiboSearch - AJAX Search for WooCommerce: by Damian Góra – 1.9.0
Async JavaScript: by Frank Goossens (futtta) – 2.20.12.09
Classic Editor: by WordPress Contributors – 1.6
Combar Plugins Package: by  – 0.9.5
Contact Form 7: by Takayuki Miyoshi – 5.4
Contact Form CFDB7: by Arshid – 1.2.5.9
The7 Elements: by Dream-Theme – 2.5.6
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.1.2
Facebook for WooCommerce: by Facebook – 2.3.4
Invisible reCaptcha: by Mihai Chelaru – 1.2.3
Jetpack by WordPress.com: by Automattic – 9.5
The7 WPBakery Page Builder: by Michael M - WPBakery.com – 6.6.0.1
Limit Login Attempts Reloaded: by Limit Login Attempts Reloaded – 2.20.6
LiteSpeed Cache: by LiteSpeed Technologies – 3.6.4
WooCommerce Load More Products: by BeRocket – 1.1.8
Merge + Minify + Refresh: by Launch Interactive – 1.12.1
The7 disable web fonts: by Dream Theme – 1.0.1
Compress JPEG & PNG images: by TinyPNG – 3.2.1
Variation Swatches for WooCommerce: by Emran Ahmed – 1.1.13
Gobit  Tranzilla: by Gobit software – 5.0.9
WooCommerce: by Automattic – 5.1.0
Yoast SEO: by Team Yoast – 16.0.2
WP Sitemap Page: by Tony Archambeau – 1.6.4

### Inactive Plugins (2) ###

Redirection: by John Godley – 5.0.1
YITH WooCommerce Catalog Mode: by YITH – 2.0.11

### Dropin Plugins (1) ###

object-cache.php: object-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: ILS (₪)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #2511 - /shop/
Cart: #2512 - /cart/
Checkout: #2513 - /checkout/
My account: ❌ Page ID is set
but the page does not exist

Terms and conditions: #5409 - /terms/

### Theme ###

Name: the7dtchild
Version: 1.0.0
Author URL: http://dream-theme.com/
Child Theme: ✔
Parent Theme Name: The7
Parent Theme Version: 9.9.1
Parent Theme Author URL: http://dream-theme.com/
WooCommerce Support: ✔

### Templates ###

Overrides: dt-the7/woocommerce/cart/cart.php
dt-the7/woocommerce/cart/cross-sells.php
dt-the7/woocommerce/cart/mini-cart.php
dt-the7/woocommerce/checkout/form-billing.php
dt-the7/woocommerce/checkout/form-checkout.php
dt-the7/woocommerce/checkout/form-coupon.php
dt-the7/woocommerce/checkout/form-login.php
dt-the7/woocommerce/checkout/form-shipping.php
dt-the7/woocommerce/checkout/review-order.php
dt-the7/woocommerce/checkout/thankyou.php
dt-the7-child/woocommerce/content-product.php
dt-the7/woocommerce/content-widget-product.php
dt-the7/woocommerce/content-widget-reviews.php
dt-the7-child/woocommerce/emails/admin-new-order.php
dt-the7-child/woocommerce/emails/customer-completed-order.php
dt-the7-child/woocommerce/emails/customer-on-hold-order.php
dt-the7/woocommerce/global/breadcrumb.php
dt-the7/woocommerce/global/form-login.php
dt-the7/woocommerce/global/quantity-input.php
dt-the7/woocommerce/loop/loop-end.php
dt-the7/woocommerce/loop/loop-start.php
dt-the7/woocommerce/loop/pagination.php
dt-the7-child/woocommerce/loop/result-count.php
dt-the7/woocommerce/myaccount/form-login.php
dt-the7/woocommerce/notices/error.php
dt-the7/woocommerce/notices/notice.php
dt-the7/woocommerce/notices/success.php
dt-the7/woocommerce/order/order-details-customer.php
dt-the7/woocommerce/order/order-details.php
dt-the7/woocommerce/single-product/meta.php
dt-the7/woocommerce/single-product/price.php
dt-the7-child/woocommerce/single-product/product-image.php
dt-the7-child/woocommerce/single-product/related.php
dt-the7/woocommerce/single-product/up-sells.php
dt-the7/woocommerce/content-product_cat.php

### Action Scheduler ###

Complete: 5,681
Oldest: 2021-03-06 14:29:37 +0200
Newest: 2021-04-06 15:26:19 +0300

Pending: 2
Oldest: 2021-04-06 15:27:44 +0300
Newest: 2021-04-06 15:39:30 +0300

### Status report information ###

Generated at: 2021-04-06 15:27:21 +03:00
</details>

**Comment by estebancano-dev** [comment] 2021-04-08 12:16
same here! On email/web, quantity is ok, but not in the app. Now we are verifying all 3 to make sure and not to send wrong items. Happens on 6.3 too

```
### WordPress Environment ###
WC Version: 5.2.0
REST API Version: ✔ 5.2.0
WC Blocks Version: ✔ 4.7.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.5
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_AR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.16
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.9-MariaDB-1:10.5.9+maria~buster
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.0
WC Database Prefix: wp_
Tamaño total de la base de datos: 9.41MB
Tamaño de los datos de la base de datos: 7.14MB
Tamaño del índice de la base de datos: 2.27MB
wp_woocommerce_sessions: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Datos: 0.14MB + Índice: 0.14MB + Motor InnoDB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_actions: Datos: 0.05MB + Índice: 0.11MB + Motor InnoDB
wp_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_logs: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_comments: Datos: 0.06MB + Índice: 0.09MB + Motor InnoDB
wp_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_litespeed_img_optm: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_litespeed_optimizer: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_options: Datos: 4.09MB + Índice: 0.14MB + Motor InnoDB
wp_postmeta: Datos: 1.50MB + Índice: 0.45MB + Motor InnoDB
wp_posts: Datos: 0.25MB + Índice: 0.09MB + Motor InnoDB
wp_smush_dir_images: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_term_relationships: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_usermeta: Datos: 0.19MB + Índice: 0.16MB + Motor InnoDB
wp_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_product_lookup: Datos: 0.05MB + Índice: 0.06MB + Motor InnoDB
wp_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wpforms_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

attachment: 118
custom_css: 2
custom-css-js: 1
nav_menu_item: 6
page: 7
post: 1
product: 19
product_variation: 61
revision: 143
shop_order: 73
wp_block: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

Header and Footer Scripts: por Digital Liberation – 2.2.1
Jetpack por WordPress.com: por Automattic – 9.6.1
LiteSpeed Cache: por LiteSpeed Technologies – 3.6.4
WooCommerce: por Automattic – 5.2.0
WP Mail SMTP: por WPForms – 2.7.0
Smush: por WPMU DEV – 3.8.4
WPForms Lite: por WPForms – 1.6.6

### Inactive Plugins (0) ###


### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: ARS ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Casa matriz de la tienda: #8 - /
Carrito: #9 - /carrito/
Finalizar compra: #10 - /finalizar-compra/
Mi cuenta: #11 - /mi-cuenta/
Términos y condiciones: ❌ Página no definida

### Theme ###

Name: Freely
Version: 1.0.1
Author URL: https://wpzita.com/
Child Theme: ✔
Parent Theme Name: Zita
Parent Theme Version: 1.5.0
Parent Theme Author URL: 
WooCommerce Support: ✔

### Templates ###

Archive Template: Tu tema tiene un archivo woocommerce.php
no podrás sobreescribir la plantilla personalizada woocommerce/archive-product.php ya que woocommerce.php tiene prioridad sobre archive-product.php. Esto es intencionado para prevenir problemas de visualización.

Overrides: –

### Action Scheduler ###

Completar: 65
Oldest: 2021-04-06 02:47:50 +0000
Newest: 2021-04-13 14:59:05 +0000

Pendiente: 4
Oldest: 2021-04-14 11:34:04 +0000
Newest: 2021-04-19 11:27:26 +0000


### Status report information ###

Generated at: 2021-04-13 23:06:28 -03:00
`

**Comment by estebancano-dev** [comment] 2021-04-22 02:00
Proof on Android app (6.4.1 now)

<img src="https://user-images.githubusercontent.com/58123463/115644679-5b74ca80-a2f5-11eb-83e9-814e11f6d738.png" width="270" alt="Screenshot_20210421-225933">

**Comment by anitaa1990** [comment] 2021-04-22 11:20
Hi there @estebancano-dev and @adinighter!

Thank you for reporting this issue! We are as such unable to reproduce the same issue and would appreciate some details from your end. Looks like https://wpzita.com/ is the store url you are facing issue with? Would you be able to confirm that? That would be helpful in debugging what could be causing this issue.

**Comment by estebancano-dev** [comment] 2021-04-22 17:03
Yeah, I cannot reproduce it too. Im using jetpack and "Freely" theme. I have nothing to do with wpzita.com. If you need to, I can send you a backup of some tables to make some tests, maybe you can connect it to android app and see whats going on. Don't know how to help you
On woocommerce it looks like this (maths are good there):
![image](https://user-images.githubusercontent.com/58123463/115755959-4b500000-a374-11eb-83dc-5ec980f99957.png)

**Comment by estebancano-dev** [comment] 2021-05-22 19:13
Im looking at the tables. Order id is 2269.
Searching at 
`SELECT * FROM wp_woocommerce_order_items where order_id=2269`
gives 
![image](https://user-images.githubusercontent.com/58123463/119238198-7b2b2880-bb17-11eb-95ee-48cdfcd79939.png)

and `SELECT * FROM wp_woocommerce_order_itemmeta where order_item_id in (330,331,332)` 
gives
![image](https://user-images.githubusercontent.com/58123463/119238235-b299d500-bb17-11eb-9ada-4a1c0c8512aa.png)

So, quantity on db seems right, that's why on email and web the order is ok (2 items and 1 item).

So, it's definetly something on the app that is not using _qty correctly?

I tried changing _qty 1 for 15 (meta_id 2864), and this happens! 

![image](https://user-images.githubusercontent.com/58123463/119238367-73b84f00-bb18-11eb-9891-3649079551df.png)

And if I change quantity on the other products (2 for 15, meta_id 2853), it looks like this:

![image](https://user-images.githubusercontent.com/58123463/119238597-cb0aef00-bb19-11eb-97c5-4466a8c52e68.png)

Its super weird the maths it's doing, the bigger the value, the total for the first product decreases. If I put _qty=50 (meta_id 2853), total price goes to $48.

If you need me to query some variations or products just ask, but I hope this helps you to find the bug that is there! Cheers

**Comment by estebancano-dev** [comment] 2021-06-05 14:06
@designsimply @anitaa1990 any comments? Do you need aditional info to be able to reproduce it ?

**Comment by designsimply** [comment] 2021-06-08 00:46
I was unable to reproduce the problem using the following testing steps:

1. Create and publish a variable product such as a t-shirt with S, M, L variations.
1. On the web, submit an order with more than one variation purchased (in my test I purchased 3 small t-shirts).
1. In the app, check to see if the order shows the correct number of products ordered.

<strong>Result:</strong> I could see the correct quantity for the order on the web and in the app.

<img src="https://user-images.githubusercontent.com/1119271/121105014-76759e00-c7c0-11eb-8e41-93d3f24bf36c.png" width="200" alt="Screenshot_20210607-183628"> <img width="500" alt="Screen Shot 2021-06-07 at Jun 7 6 32 13 PM" src="https://user-images.githubusercontent.com/1119271/121104981-63fb6480-c7c0-11eb-8b06-799710323aa9.png">

<sup>Tested with WCAndroid 6.8-rc-1 on Pixel 3 Android 11.</sup>

@estebancano-dev I saw the database info in your system status report says this:

> MySQL Version: 5.5.5-10.5.9-MariaDB-1:10.5.9+maria~buster

The [WordPress minimum requirements](https://wordpress.org/about/requirements/) mention that you need MySQL version 5.6 or greater OR MariaDB version 10.1 or greater—do you think that could be the source of the problem in your case?

**Comment by estebancano-dev** [comment] 2021-06-08 02:02
My MySQL version is 10.5.9, so that's for sure not the issue. Can I send
you some dump of tables you need so you can continue testing it? Or maybe
related registers of that order

**Comment by anitaa1990** [comment] 2021-06-11 05:43
Hey @estebancano-dev  would you be able to send us the url for your store so we can test why this is happening? We're unable to reproduce this issue from our own stores.

**Comment by estebancano-dev** [comment] 2021-06-11 11:58
@anitaa1990  Sent you an email

**Comment by anitaa1990** [comment] 2021-06-14 10:57
Thank you for the details @estebancano-dev! We found that the issue was indeed with the app and have opened a PR in #4193 with a fix. It should be released into beta within the next few hours. Thank you for taking the time to debug the problem and share all the details that helped us in fixing it 😄

**Comment by estebancano-dev** [comment] 2021-06-14 11:48
Wow amazing, glad I was able to contribute to fix the issue!!

**Closed as completed** 2021-06-14 16:59 UTC
Labels: type: bug, feature: order details
