### ISSUE TITLE
Skeleton view overlap

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#6903] opened 2022-07-08 18:16 UTC
While working on product search by SKU (#6838) I noticed the skeleton view was overlapping the search tabs:

![Screenshot_20220707-165942](https://user-images.githubusercontent.com/3903757/178047715-42a11544-3e85-47c3-81b1-6ffcfe657815.png)

I verified in preview that the tabs were directly above the recycler with no overlap:

<img width="305" alt="preview" src="https://user-images.githubusercontent.com/3903757/178047859-19d1ceff-63ee-44c5-96db-328547835a89.png">

I believe the problem may be [here](https://github.com/woocommerce/woocommerce-android/blob/0a85b39af97b2232000ca33fbd2e22b4f59ecabf/WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/SkeletonView.kt#L67). We tell the skeleton which view it's supposed to replace (the recycler, in this case), and then we add it to the parent view without taking the top of replaced view into account.

**Comment by samiuelson** [comment] 2022-10-12 10:47
FYI, I couldn't reproduce this on the latest `trunk` (Google Pixel 4a API 33). Not sure if it's solved already.

**Comment by backwardstruck** [comment] 2024-01-09 21:20
For this one, do we know if it's still happening @nbradbury ? If so, what are the steps to reproduce? I am still setting up my Woo Commerce site for testing.

**Comment by samiuelson** [comment] 2024-02-15 09:07
I think it's not happening anymore. I'm closing it for now.

**Closed as completed by samiuelson** 2024-02-15 09:07 UTC
Labels: type: bug, good first issue
