### ISSUE TITLE
[Card Present Payments] Updating a reader ends up in a loop

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#4328] opened 2021-06-30 19:54 UTC
**To Reproduce**
1. Have an outdated reader.
2. Go to `Manage card reader`.
3. Connect a reader.
4. Click on `Update` on `Software update` dialog.
5. See that after the update is finished, a `Software update` dialog is displayed again.

**Demo**

https://user-images.githubusercontent.com/5845095/124022340-f7553d80-d9ec-11eb-8889-87954b8fdbf7.mov

**Expected behavior**
A reader should be updated.

Note: I had 100% repro on this (happened every time with like 10 tries). After restarting the app, it didn't prompt me about the update anymore so it seems that a reader is updated - it's more of UI logic thing I suppose.

**Comment by wzieba** [comment] 2021-07-05 12:30
@kidinov @malinajirka - do you know some way to force an update to an outdated version of reader's software? This way we could try to reproduce this issue.

**Comment by kidinov** [comment] 2021-07-06 07:54
@wzieba thanks for the report! I'm wondering if you can/could reproduce this bug with this PR being merged https://github.com/woocommerce/woocommerce-android/pull/4287 ?

In meanwhile I'll check the documentation if there is a way to downgrade my reader, because I can not test this case otherwise

**UPDATE:** No we can not downgrade a reader. The simulator always responds with "update available" so the behavior like you found is correct for the simulator. It looks like that for some reason the SDK responds with "update available" even after an update has happened for a real device. Investigating

**UPDATE2:** I see that in the sample app they just hide "update button" after the update. Maybe we should do the same? Or maybe just wait for SDK 2.0 integration and see if it's fixed there @malinajirka

**Comment by malinajirka** [comment] 2021-07-07 08:31
> UPDATE2: I see that in the sample app they just hide "update button" after the update. Maybe we should do the same? Or maybe just wait for SDK 2.0 integration and see if it's fixed there @malinajirka

Hiding the button sounds good to me. It might take a while before we migrate to v2.

**Closed as completed** 2021-07-08 05:22 UTC
Labels: type: bug, feature: mobile payments
