### ISSUE TITLE
Products: Sale dates changed by 1 day from dates selected in date picker

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2988] opened 2020-10-08 16:09 UTC
**Describe the bug**
h/t @jaclync for reporting this:

> Edit product > price: the sale start date I picked from the date picker became the day before, and the sale end date I picked became the day after. The site time zone is the same as my device time zone (GMT+8).

I reproduced the issue with my test store and device, which are both set to UTC+1. I also confirmed that the incorrect sale dates are the ones saved remotely.

**To Reproduce**

Navigate to the products tab.
Tap on a product.
Tap on Price.
Enable the "Schedule sale" toggle.
Tap on the "From" field to open the date picker.
Select a "from" date and notice that the "From" field shows the day before the one selected.
Tap on the "To" field to open the date picker.
Select a "to" date and notice that the "To" field shows the day after the one selected.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.2-rc-1

**Comment by nbradbury** [comment] 2020-10-15 18:13
@anitaa1990 I've been looking into this, and the problem appears to be our use of [DateUtils.localDateToGmt()](https://github.com/woocommerce/woocommerce-android/blob/7193885f30e6f160e7c3bc94450c620a7c94bec4/WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt#L304). If I change that to use [the date returned here](https://github.com/woocommerce/woocommerce-android/blob/7193885f30e6f160e7c3bc94450c620a7c94bec4/WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt#L314) without an offset, the problem goes away.

However, I didn't want to make that change without passing it by you first since you wrote the code and may know better than me what the fix should be.

**Comment by anitaa1990** [comment] 2020-10-16 10:11
@nbradbury, thanks for looking into this. 

>  the problem appears to be our use of DateUtils.localDateToGmt(). If I change that to use the date returned here without an offset, the problem goes away.

The idea was to ensure that when we update the date to the backend, it should be in GMT format, since we are [updating the `date_on_sale_to_gmt` and `date_on_sale_from_gmt` fields in the product API](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/0e0484f6f9ca07500945d6c1d9c1373ecaae410b/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/ProductRestClient.kt#L1136).

**Comment by anitaa1990** [comment] 2020-10-16 10:15
That being said, I am not really able to reproduce this issue from UTC+5.30 timezone, which makes me think it might have something to do with specific timezones 🤔 

<img src="https://user-images.githubusercontent.com/22608780/96246632-8ab52280-0fc6-11eb-927e-6369d02066c7.gif" width="300"/>

**Comment by rachelmcr** [comment] 2020-10-16 11:16
@anitaa1990 What is the timezone setting on your site (under Settings > General in wp-admin)? I just tested with a site set to UTC+0 and didn't see the issue. But when I change that site's timezone to UTC+1, and log out and back in to the app, I start seeing this issue with products on that site.

**Comment by nbradbury** [comment] 2020-10-16 11:25
FYI: In my case I didn't see the issue until I set both my store and the device to UTC+1.

**Comment by anitaa1990** [comment] 2020-10-21 11:06
> @anitaa1990 What is the timezone setting on your site (under Settings > General in wp-admin)? I just tested with a site set to UTC+0 and didn't see the issue. But when I change that site's timezone to UTC+1, and log out and back in to the app, I start seeing this issue with products on that site.

Sorry for the late reply folks! This got lost in the mail 🤦‍♀️!  My timezone setting on my test site was UTC-6. I changed it to UTC+1 and as @nbradbury suggested changed the local timezone to UTC+1 as well but was not able to reproduce the issue. I tried changing the timezone in the device to anything else and was still unsuccessful. 

I changed my store to a different one, with the timezone setting set to `UTC+8` and device timezone to `UTC+5.30` and was able to reproduce the issue. 

It looks like removing the hour, minute and operator value [here](https://github.com/woocommerce/woocommerce-android/blob/6ddfc7de3cecc8561a336287cb48fe54f6e43ccd/WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt#L315), the issue is fixed for all the timezones. @nbradbury, since you're assigned to this issue, I was able to modify this [method](https://github.com/woocommerce/woocommerce-android/blob/6ddfc7de3cecc8561a336287cb48fe54f6e43ccd/WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt#L304) to the following, to fix this issue:
```
    fun localDateToGmt(
        year: Int,
        month: Int,
        day: Int,
        gmtOffset: Float,
        timeAtStartOfDay: Boolean
    ): Date {
        val date = GregorianCalendar(year, month, day).time
        return offsetGmtDate(date, gmtOffset)
    }
```

**Comment by AliSoftware** [comment] 2020-11-02 15:21
@rachelmcr @anitaa1990 Moving this to 5.5 since 5.4 is ❄️-ing today

**Comment by AliSoftware** [comment] 2020-11-16 15:28
Seems this still hasn't got a chance to get picked before today's 5.5 ❄️  code freeze, so pushing it further to milestone 5.6

**Comment by ovitrif** [comment] 2022-04-04 15:11
> @anitaa1990 What is the timezone setting on your site (under Settings > General in wp-admin)? I just tested with a site set to UTC+0 and didn't see the issue. But when I change that site's timezone to UTC+1, and log out and back in to the app, I start seeing this issue with products on that site.

I'm trying to look into this issue and I also couldn't reproduce it on my test site, which was originally `UCT+0`.

Trying now with `UTC+1`, and I'll report back my findings 🙇‍♂️

**Comment by ovitrif** [comment] 2022-04-04 17:07
>I'm trying to look into this issue and I also couldn't reproduce it on my test site, which was originally UCT+0.
>
>Trying now with UTC+1, and I'll report back my findings 🙇‍♂️

Yep, that reproduced:

https://user-images.githubusercontent.com/4588074/161595531-20dedd95-1340-455c-bbec-4c7a77593235.mp4

I'll look deeper into it tomorrow.

**Tested on:**
📱 Samsung Galaxy S8+, Android 9,
⏰ Site Timezone: UTC+1, Device Timezone: UTC+2
💻 WCAndroid app built from commit [48baa16](https://github.com/woocommerce/woocommerce-android/commit/48baa161bcffd6f45ea34b81affb7dddf960543b)

**Comment by ovitrif** [comment] 2022-04-06 18:48
> It looks like removing the hour, minute and operator value [here](https://github.com/woocommerce/woocommerce-android/blob/6ddfc7de3cecc8561a336287cb48fe54f6e43ccd/WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt#L315), the issue is fixed for all the timezones. @nbradbury, since you're assigned to this issue, I was able to modify this [method](https://github.com/woocommerce/woocommerce-android/blob/6ddfc7de3cecc8561a336287cb48fe54f6e43ccd/WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt#L304) to the following, to fix this issue:
> ```kotlin
> fun localDateToGmt(
>     year: Int,
>     month: Int,
>     day: Int,
>     gmtOffset: Float,
>     timeAtStartOfDay: Boolean
> ): Date {
>     val date = GregorianCalendar(year, month, day).time
>     return offsetGmtDate(date, gmtOffset)
> }
> ```

@anitaa1990 I've approached testing this suggestion with TDD by first creating a unit test which verifies the result of `localDateToGmt()` given all possible hourly offsets... I used a loop through `-12..+12`.

The 🔴 results of the unit test showed that for every time zone with a negative hourly offset the resulting `dayOfMonth` of the returned `Date` object is different than the day we are inputting (which is in fact the day selected by the user via the date picker).

Proceeded to verify this by setting my store to a TimeZone of `-2` and confirmed that's the case by live testing the app.

I could easily fix that with removing the `return offsetGmtDate(date, gmtOffset)` and just returning the date.
I tested this and it seems to me it's more or less what the user expects, regardless of the time zone of the site. I'm saying this **only** from the perspective of the dates we save & what is shown on the UI afterwards. I didn't actually test how that applies to the product price during the scheduled sales dates because I don't know an easy way to do that.

Another small concern I have with this approach is that what I presume you initially tried to achieve by setting the hour, minute & second with these lines of code was something that could be a nice "feature" for merchants:
```kotlin
val hour = if (timeAtStartOfDay) 0 else 23
val minuteSecond = if (timeAtStartOfDay) 0 else 59
```

Although I'm not 💯 sure what would be expected and don't have a good idea who to ping about this but at the moment that's my biggest concern with going with a simple solution.

If we concur the user would rather expect the sale period to end at the start of the selected day, then I'm quite confident we can go with a simple implementation of just returning `GregorianCalendar(year, month, day).time`.

I'll verify this assumption but I tend to think we don't really need to call `offsetGmtDate()`, especially because according to the docs of the method, it expects a date in GMT, which we don't get with `GregorianCalendar()`:
```kotlin
/**
 * Returns a date with the passed GMT offset applied - note that this assumes the passed date is GMT
 * ...
 */
```

**Comment by ovitrif** [comment] 2022-04-06 20:27
I've went down the stack trace when a product is updated & found that we're calling `Product.toDataModel()` in `ProductDetailRepository.updateProduct()`, which calls `Date.formatToYYYYmmDDhhmmss()` for both properties: `dateOnSaleFromGmt` and `dateOnSaleToGmt`.

That extension method removes time zone info, which makes me think it's ok to go forward with using `GregorianCalendar(year, month, day).time` for setting the sale dates selected in the picker:

```kotlin
fun Date.formatToYYYYmmDDhhmmss(): String =
    SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss", Locale.getDefault()).format(this)
```

**Closed as completed** 2022-04-08 12:54 UTC
Labels: type: bug, feature: product details, good first issue

**Comment by ovitrif** [comment] 2022-04-08 18:08
> If we concur the user would rather expect the sale period to end at the start of the selected day, then I'm quite confident we can go with a simple implementation of just returning GregorianCalendar(year, month, day).time.


To close the loop here, I've discussed this issue with @anitaa1990 in more detail and we concluded to go forward with using dates at midnight, since that is in sync with what happens on the web side of a WooCommerce store.
