### ISSUE TITLE
Customer Search in Order Creation flow doesn't prefill the customer details

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#7962] opened 2022-11-28 11:35 UTC
**Describe the bug**
When I search for a customer in the order creation flow and select a customer, for some customers nothing gets prefilled -> all the input fields are empty.

**To Reproduce**
1. Go to 'Order List'
2. Click on 'Click on Plus sign action'
3. Click on "Add Customer details"
4. Click on "Search icon"
5. Search for some customer
6. Select it
7. Check if the input fields are empty or prefilled (repeat the above steps until you find a customer for which the inputs are empty)

**Screenshots**
https://user-images.githubusercontent.com/2261188/204267615-10ca6252-6821-4950-af68-8bb4a04b8e1e.mp4

**Expected behavior**
I'd expect all the details which are set to be prefilled automatically after I select an existing customer using the search.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 6 Pro
- Android version: 13
- WooCommerce Android version: 11.3-rc-1

**Comment by malinajirka** [comment] 2023-06-13 11:52
@kidinov since you recently dove into the implementation details. Do you know if this issue is fixed or will be fixed with the planned changes? Seems like at least "first name, last name and email" should be prefilled since they are available. Wdyt?

**Comment by kidinov** [comment] 2023-06-13 12:13
@malinajirka is this reproducible on the latest trunk? If yes, please invite me to the site so I can test

**Comment by malinajirka** [comment] 2023-06-15 07:01
@kidinov Yes, it is. I've invited you to the site - an example customer is `Jiri Malina with email address malinajirkatest32@gmail.com`. Thanks!

**Comment by kidinov** [comment] 2023-06-15 11:02
For historical reasons:

It seems less or more clear why it doesn't work. The API doesn't return the First and Last names in the shipping and billing address objects, which used to fill the customer's First and Last name fields.  The API returns first and last name fields as part of the root object and this could and probably should be used to fill the data.

```
{
  "data": [
    {
      "id": 6,
      "date_created": "2020-09-24T09:58:58",
      "date_created_gmt": "2020-09-24T09:58:58",
      "date_modified": "2020-09-24T09:58:58",
      "date_modified_gmt": "2020-09-24T09:58:58",
      "email": "malinajirkatest32@gmail.com",
      "first_name": "Jiri",
      "last_name": "Malina",
      "role": "administrator",
      "username": "malinajirkatest32",
      "billing": {
        "first_name": "",
        "last_name": "",
        "company": "",
        "address_1": "",
        "address_2": "",
        "city": "",
        "postcode": "",
        "country": "",
        "state": "",
        "email": "",
        "phone": ""
      },
      "shipping": {
        "first_name": "",
        "last_name": "",
        "company": "",
        "address_1": "",
        "address_2": "",
        "city": "",
        "postcode": "",
        "country": "",
        "state": "",
        "phone": ""
      },
      "is_paying_customer": false,
      "avatar_url": "https:\/\/secure.gravatar.com\/avatar\/5900c4cf90d515caee182e787f186e1b?s=96&d=mm&r=g",
      ...
}
```
But here is the catch. The new API that we use wc_analytics/reports/customers doesn't return this customer at all.
It doesn't show up on the [customers](https://site-for-woocommerce12a3fasdf45dfs6789.mystagingwebsite.com/wp-admin/admin.php?page=wc-admin&path=%2Fcustomers&per_page=100&paged=1) page in wp_admin (it use the same API). I thought that it could be because malinajirkatest32 didn't make any purchases, but I see other customers on the list with 0 spend so I don't understand at the moment why there is this difference.
The new API returns less info

```
    {
      "id": 2,
      "user_id": 0,
      "username": "",
      "name": "Test Test",
      "email": "test@testaddress.com",
      "country": "CZ",
      "city": "Prague",
      "state": "",
      "postcode": "11000",
      "date_registered": null,
      "date_last_active": "2020-10-06T07:58:42",
      "date_last_order": "2021-03-15 18:19:22",
      "orders_count": 1,
      "total_spend": 108.90000000000002,
      "avg_order_value": 108.90000000000002,
      "date_registered_gmt": null,
      "date_last_active_gmt": "2020-10-06T07:58:42"
    }
```
That's why if it's a registered customer, then we fetch info about that after it's selected by a user from the backend. If not, then we just use what we have (city, country, etc)
The fix maybe not be needed when we use the new API, because the API may not return customers like that. But we are not sure, so probably better to specifically return the first/last name instead of using the one from the shipping/billing address info.

**Comment by kidinov** [comment] 2023-06-15 11:05
I checked the iOS code and the implementation currently matches what we have in this PR - https://github.com/woocommerce/woocommerce-android/pull/9212

Under the assumption that the new API doesn't return customers like @malinajirka has on his site (with first/last name but without billing and shipping address doesn't have the names) closing this issue. At the end on the UI we show shipping and billing address and the customer don't have this info in the API

**Closed as completed by kidinov** 2023-06-15 11:05 UTC
Labels: type: bug, feature: order creation, feature: order editing
