### ISSUE TITLE
[Coupons] Restrictions: Add toggles to set "Individual Use Only" and "Exclude Sale Items".

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#6543] opened 2022-05-19 03:27 UTC
![Screen Shot 2022-05-19 at 10 22 37](https://user-images.githubusercontent.com/266376/169197957-4c14d7ad-be8c-4490-b1bb-8b9d3d6b3831.png)

**Comment by hichamboushaba** [comment] 2022-05-23 09:13
Duplicate of #5543 and #6555

**Closed as completed by hichamboushaba** 2022-05-23 09:13 UTC
Labels: type: enhancement, feature: coupons
