### ISSUE TITLE
Shipment tracking deletion issue

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#2863] opened 2020-09-18 12:54 UTC
Deleting a shipment tracking from the fulfillment screen produces a bad state:

1. Open an order with at least 2 shipment trackings (or create them)
2. Go to order fulfillment and delete one of them
3. Go back to the order detail
4. Notice that both trackings are still there
5. After a while, the whole tracking section disappears

**Comment by anitaa1990** [comment] 2020-10-26 02:27
Closing this one since we removed the Order Fullfill screen from the app and I am no longer able to reproduce this issue.

**Closed as completed by anitaa1990** 2020-10-26 02:27 UTC
Labels: type: bug, feature: order details
