### ISSUE TITLE
[Product Variations] Both, empty and variations list views coexist on screen

### ISSUE THREAD

**Issue by ParaskP7** [woocommerce/woocommerce-android#3197] opened 2020-11-24 12:13 UTC
**Describe the bug**
When a user enters the product variation screen which is empty, and then, creates product variations using the web interface, after refreshing the screen, with a pull-to-refresh, both the `empty` and `variations list` views, coexist on the same screen. The same applies the other way around. For example, when a user enters the product variation screen which has some variations already, and then, deletes all product variations using the web interface, after refreshing the screen, with a pull-to-refresh, both the `empty` and `variations list` views, coexist on the same screen.

Going back to the previous screen, and into the product variation screen again, fixes this inconsistency.

**To Reproduce**
1. Go to `Products` tab.
2. Find a product with variations (or create one).
3. Go to `Variations` screen.
4. Make sure the are not variations and the screen is empty (empty view is shown).
5. Go to `Products` section in web.
6. Find the product used above.
7. Go to `Variations` section (make sure no variations are present).
8. Create variations for the product.
9. Check `Variations` screen in app and trigger pull-to-refresh.
10. See both, the empty and variations list views coexist on the screen.

**Screenshots**
<img src="https://user-images.githubusercontent.com/9729923/100092880-7256e400-2e5f-11eb-817e-107b5d9afd80.png" width="250" height="500">

**Expected behavior**
On step 10. above, either the empty or the variations list view should exist on the screen. Depending on the scenario (empty to variations, or variations to empty).

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 4
- Android version: 11
- WooCommerce Android version: 5.5-rc-1

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://petrosatwork.blog
Site address (URL): https://petrosatwork.blog
WC Version: 4.7.0
REST API Version: ✔ 4.7.0
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.12
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.73.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.24-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.0
WC Database Prefix: wp_
Total Database Size: 6.78MB
Database Data Size: 4.38MB
Database Index Size: 2.40MB
wp_woocommerce_sessions: Data: 0.41MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.09MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.27MB + Index: 0.20MB + Engine InnoDB
wp_posts: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbscrm_api_keys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_admlog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_aka: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_companies: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_customfields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_dbmigration_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_dbmigration_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_events: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_event_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_externalsources: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_invoices: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_zbs_lineitems: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_object_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_quotes: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_zbs_quotes_templates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_security_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_segments_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_settings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_sys_cronmanagerlogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_sys_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_sys_email_hist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_tags_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_tax_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_temphash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_transactions: Data: 0.02MB + Index: 0.14MB + Engine InnoDB

### Post Type Counts ###

attachment: 31
customize_changeset: 3
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
jp_vid_sitemap: 2
nav_menu_item: 5
page: 8
post: 3
product: 23
product_variation: 57
revision: 7
shop_coupon: 4
shop_order: 5
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Akismet Anti-Spam: by Automattic – 4.1.7
AMP: by AMP Project Contributors – 2.0.7
CoBlocks: by GoDaddy – 2.5.3
Crowdsignal Forms: by Automattic – 1.3.3
WordPress.com Editing Toolkit: by Automattic – 2.8.8
Gutenberg: by Gutenberg Team – 9.3.0
Jetpack by WordPress.com: by Automattic – 9.1
Layout Grid: by Automattic – 1.3
Page Optimize: by Automattic – 0.5.1
WooCommerce Stripe Gateway: by WooCommerce – 4.5.5 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Shipping & Tax: by Automattic – 1.25.2 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce: by Automattic – 4.7.0
Jetpack CRM: by Automattic – 4.0.7

### Inactive Plugins (1) ###

Classic Editor: by WordPress Contributors – 1.6

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #54 - /shop/
Cart: #55 - /cart/
Checkout: #56 - /checkout/
My account: #57 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.9.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 12
Oldest: 2020-11-16 11:31:35 +0200
Newest: 2020-11-23 16:15:13 +0200

`
```
</details>

**Comment by rossanafmenezes** [comment] 2021-08-07 20:17
tested this on several devices, including a pixel 4 and was not able to reproduce it anymore. Closing it.

**Closed as completed by rossanafmenezes** 2021-08-07 20:17 UTC
Labels: type: bug, good first issue, category: design, feature: variation list
