### ISSUE TITLE
Orders List: Order Status is not updated immediately upon marking as paid

### ISSUE THREAD

**Issue by thehenrybyrd** [woocommerce/woocommerce-android#7166] opened 2022-08-11 13:08 UTC
**Describe the bug**
Order Status status is not updated immediately in Orders list after completing via "Collect Payment" > "Cash".

**To Reproduce**
1. In Orders, create an order with one or more item.
2. After creating the new Order, use "Collect Payment" > "Cash" to quickly mark the order as paid.
3. On the Orders screen, note the status is still "pending payment"
4. Pull-to-refresh to see the updated status.

**Screenshots**

https://user-images.githubusercontent.com/15107387/184140202-dbe77286-8051-4583-9c4d-bd192b38af4e.mp4

**Expected behavior**
I expected to see the new order status as soon as I arrived back on the Orders screen.

**Mobile Environment**
Samsung Galaxy S21, Android 12, WC Android 9.8-rc-1

**Comment by dangermattic** [comment] 2024-02-16 12:01
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by backwardstruck** [comment] 2024-02-16 20:40
I'm not able to reproduce but it's also not clear to me that it was fixed. I just see the order after waiting a while, then it is in the correct status `Completed`.

**Comment by malinajirka** [comment] 2024-02-21 11:01
I'm re-assigning this to myself since Joel is on unexpected AFK and this issue is currently blocking a release of the tablet support project.

**Comment by jd-alexander** [comment] 2024-02-21 14:50
No problem. Thanks @malinajirka This is how far I had gotten in the [issue](https://github.com/woocommerce/woocommerce-android/compare/issue/10568-nav-host-fragment...issue-7166/order-list-not-updated-after-mark-as-paid?expand=1). (Primarily referencing the code in the files changed section.)

**Comment by toupper** [comment] 2024-04-17 09:49
@malinajirka Is this issue done? Can we close it? :)

**Comment by malinajirka** [comment] 2024-07-18 08:48
I completely missed this ping, yes this is fixed now.

**Closed as completed by malinajirka** 2024-07-18 08:48 UTC
Labels: type: bug, feature: order list, good first issue
