### ISSUE TITLE
Product images: sometimes the media library doesn't show all of the available images

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#3535] opened 2021-02-05 20:20 UTC
Steps to reproduce:

* This issue will be easiest to observe using a site that has 10 to 20 images in the media library, give-or-take.

1. Open any product.
1. Tap the + in the Photos section then tap the "Add photos" button.
1. Upload an image using "Choose from device".
1. Upload an image using "Take a photo".
1. Start uploading an image using "WordPress media library".
1. Before selecting the image, verify that you can see all of the available images in the media library.
1. Select the image and insert it.
1. Try uploading an image using "WordPress media library" again until you see the correct number of available images.

**Result:** sometimes the media library doesn't show all the available images. ([48s](https://cloudup.com/cGXoHxnvOmp))

**Note:** I was unable to replicate this issue consistently so the steps above are what I did when I saw the problem happen. 

"WordPress media library" 1st try|"WordPress media library" 2nd try
---|---
<img src="https://user-images.githubusercontent.com/1119271/107084444-4be4eb80-67b4-11eb-9b33-92574381b5f9.png" width="100%" alt="image">|<img src="https://user-images.githubusercontent.com/1119271/107084451-4daeaf00-67b4-11eb-950f-495323461509.png" width="100%" alt="image">

<sup>Tested with WCAndroid 5.9-rc-3 on Pixel 3 Android 11 on comparative-moth.jurassic.ninja (WP 5.6 JP 9.4 WC 5.0.0-rc.1) logged in as testuser01121.</sup>

Possibly related lines from my app logs: 

```
[Feb-04 19:27 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"ProductImagesFragment"}
[Feb-04 19:27 PRODUCTS e] CancellationException while fetching site media - exception: Job was cancelled
[Feb-04 19:27 PRODUCTS e] StackTrace: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@e7d3b88
 
[Feb-04 19:27 PRODUCTS e] CancellationException while fetching site media - exception: Job was cancelled
[Feb-04 19:27 PRODUCTS e] StackTrace: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@e7d3b88
 
[Feb-04 19:27 WP v] MEDIA Fetched media list for site with size: 0
```

<sup>(internal reference: p5T066-1K3-p2#comment-7025 ← full app logs avail here)</sup>

**Comment by anitaa1990** [comment] 2022-03-14 08:30
I am not able to reproduce this issue anymore using the latest version of the app (v8.5). So will close it for now

**Closed as completed by anitaa1990** 2022-03-14 08:30 UTC
Labels: type: bug, feature: product details
