### ISSUE TITLE
US currency is typically displayed as $123 and not US$123

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#3711] opened 2021-03-17 23:52 UTC
Steps to reproduce:

1. Be on a store that has the currency set to USD.
1. Browse through the app and observe how the currency is displayed.
1. Compare to how the currency is displayed for the same store in the Android app.

**Result:** the currency displayed is `US$` on Android instead of `$` like on iOS. I also noticed that the separator is `,` in the Top Performers but `.` elsewhere.

Top Performers|Product Details|Order Details
---|---|---
![Screenshot_20210317-174209](https://user-images.githubusercontent.com/1119271/111552951-03243900-8749-11eb-8c98-d2f6b9c20905.png)|![Screenshot_20210317-174243](https://user-images.githubusercontent.com/1119271/111552947-00c1df00-8749-11eb-88bc-0902136f486e.png)|![Screenshot_20210317-174126](https://user-images.githubusercontent.com/1119271/111552955-03bccf80-8749-11eb-9d2f-9fb5244b4832.png)

<sup>Tested with WCAndroid 6.2-rc-1 on Pixel 3 Android 11.</sup>

Top Performers|Product Details|Order Details
---|---|---
![IMG_4085](https://user-images.githubusercontent.com/1119271/111552959-04556600-8749-11eb-8d4f-c0b836b78336.PNG)|![IMG_4084](https://user-images.githubusercontent.com/1119271/111552958-04556600-8749-11eb-998f-177eced75968.PNG)|![IMG_4086](https://user-images.githubusercontent.com/1119271/111552961-04556600-8749-11eb-9863-a6509a1d0522.PNG)

<sup>Tested with WCiOS 6.2.0.0 TestFlight beta on iPhone 6S iOS 13.7.</sup>

**Comment by 0nko** [comment] 2021-03-18 16:01
I can't reproduce this. Perhaps it's something with your store settings. Have you tried a different store?

![image](https://user-images.githubusercontent.com/1522856/111657242-8ad27c00-880b-11eb-9803-93bb456d596b.png)

**Comment by anitaa1990** [comment] 2021-03-19 03:23
cc @pmusolino since you had faced this bug on your test store when your language was set to Italian.

**Comment by anitaa1990** [comment] 2021-03-19 03:23
I was able to reproduce this issue when I set my device language to Italian or French I see `$US`.

**Comment by 0nko** [comment] 2021-03-19 21:15
Is that still a bug then?

**Comment by JorgeMucientes** [comment] 2024-10-29 16:52
This was fixed a long time ago. Closing

**Closed as completed by JorgeMucientes** 2024-10-29 16:52 UTC
Labels: type: bug, category: design
