### ISSUE TITLE
Aztec editor scrolls to the end of long product titles

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#2201] opened 2020-04-06 17:56 UTC
If you view product detail for a product with a long name, the detail fragment shows the title scrolled to the end.

![Screenshot_1586195655](https://user-images.githubusercontent.com/3903757/78589535-576f2b00-780e-11ea-8265-257fb59d3492.png)

**Comment by anitaa1990** [comment] 2020-04-28 03:13
I'm not able to reproduce this after the dark mode changes in he latest `develop` so closing this issue.

<img src="https://user-images.githubusercontent.com/22608780/80443213-51133100-892c-11ea-9b94-9e53a8cf469f.gif" width="300"/>

**Closed by anitaa1990** 2020-04-28 03:14 UTC
Labels: Product Details
