### ISSUE TITLE
[Coupons] Restrictions: Add screen for viewing/editing usages restriction for a coupon

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#5532] opened 2021-12-27 06:02 UTC
I want to view and edit the usage restrictions of the coupon, including the exclusions and usage limits.

![Create Coupon - Usage Restrictions](https://user-images.githubusercontent.com/266376/168190538-6102f129-7286-42d4-8278-65b4a60f8a33.png)

**Comment by hichamboushaba** [comment] 2022-04-25 17:24
After updating tickets, this seems like a duplicate of #5532

**Comment by hafizrahman** [comment] 2022-05-13 00:58
Updated original post with the latest design.

**Closed as completed** 2022-05-19 10:17 UTC
Labels: type: enhancement, feature: coupons
