### ISSUE TITLE
Copy order details to clipboard (addresses, phone, e-mail address)

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#23] opened 2017-11-13 18:27 UTC

**Comment by rachelmcr** [comment] 2019-03-13 10:07
There isn't a quick/one-tap way to copy order details to clipboard. However, I confirmed that from the order details I can:

* Manually select/copy the address, phone, and email
* Call/message the phone number
* Email the email address

**Comment by mindgraffiti** [comment] 2019-04-29 14:34
Closing because we have the main interactions complete.

**Closed by mindgraffiti** 2019-04-29 14:34 UTC
Labels: Order Details, [Type] Enhancement
