### ISSUE TITLE
Crash In Connected Sites When Rotating

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#4032] opened 2021-05-13 22:34 UTC
**Describe the bug**

The app crashes when rotating the device during the Connected Sites screen.

p1620926747172200-slack-C6H8C3G23

**To Reproduce**

1. Log in with WordPress.com 
2. In the Connected Sites section, rotate the device.

@nbradbury and I were able to reproduce this. 

**Expected behavior**

Not crash. 😁 

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 3
- Android version: 
- WooCommerce Android version: 6.6-rc.2

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by samiuelson** [comment] 2022-10-13 18:00
I'm closing the ticket since I couldn't reproduce this in WooCommerce version 10.5, Google Pixel 4a 5G, API 33.

**Closed as completed by samiuelson** 2022-10-13 18:00 UTC
Labels: type: crash, good first issue, feature: login
