### ISSUE TITLE
[Woo POS] Move state from composable ProductsInfoDialog to VM. Wrap in with Box and hide on click outside

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12268] opened 2024-08-09 10:15 UTC

**Comment by dangermattic** [comment] 2024-08-09 10:15
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by AnirudhBhat** [comment] 2024-08-13 08:20
Duplicate of https://github.com/woocommerce/woocommerce-android/issues/12291

**Closed as completed by AnirudhBhat** 2024-08-13 08:20 UTC
Labels: feature: point of sale
