### ISSUE TITLE
Cha-ching sound going missing after last two updates

### ISSUE THREAD

**Issue by webwit** [woocommerce/woocommerce-android#9735] opened 2023-09-06 13:08 UTC
**Describe the bug**
The cha-ching sound of the Woocommerce Android app goes away after I install an app update. This happened the last two updates. I searched for this, there have been more reports about this the past years and presumably fixed. When I go to the app notification settings, all is well. Under the "sound" setting it says the sound is supplied by the app. If I go to this setting and try change the volume, it is silent. When I pick an Android sound instead and try the volume, I hear the sound in the chosen volume.

I tried the fix I read about in earlier reports, which is to re-install the app. This indeed fixes it.

**To Reproduce**
1. When the app asks to install an update, update it.
2. The cha-ching sound is AWOL.

**Expected behavior**
The cha-ching sound should survive updates.

**Mobile Environment**
- Device: Samsung Galaxy S21
- Android version: 13
- WooCommerce Android version: latest

**Comment by webwit** [comment] 2023-09-06 13:34
Edit: re-installing fixed it last time, but not this time.

Edit 2: second re-install did the trick.

**Comment by hichamboushaba** [comment] 2023-12-12 09:54
This is a duplicate of #1076, and we shipped a new feature to help fix #10327 the issue without re-installing the app.

**Closed as completed** 2023-12-12 09:54 UTC

**Comment by webwit** [comment] 2023-12-13 19:36
Just got this update. Same thing, cha-ching sound going missing.

Removed app and reinstalled twice, no cha-ching.

**Comment by hichamboushaba** [comment] 2023-12-13 20:04
@webwit the changes mentioned above will be included in 16.6, which will be released next week, this week it's still on Beta, can you re-test this when you get the update and come back to us if the issue persists? Thanks 🙏
