### ISSUE TITLE
Edit products: price fragment always shows discard dialog

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#2243] opened 2020-04-14 19:02 UTC
If you've never set a product price, the pricing fragment always shows the discard dialog, even when no changes have been made.

![Screenshot_1586890755](https://user-images.githubusercontent.com/3903757/79263380-b4975c00-7e60-11ea-8f45-cef0785a916a.png)

**Comment by anitaa1990** [comment] 2020-04-15 04:41
Closing this issue since it is a duplicate of #2213 and @0nko has an open PR for that [here](https://github.com/woocommerce/woocommerce-android/pull/2231)

**Closed by anitaa1990** 2020-04-15 04:41 UTC
Labels: Product Details
