### ISSUE TITLE
[Tablet Support M2] Crash: ConcurrentModificationException – ProductImageMap is not thread-safe

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#10895] opened 2024-02-22 17:51 UTC

**Comment by dangermattic** [comment] 2024-02-22 17:51
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by malinajirka** [comment] 2024-02-23 08:20
Duplicate of https://github.com/woocommerce/woocommerce-android/issues/10901

**Closed as completed by malinajirka** 2024-02-23 08:20 UTC
Labels: type: crash, category: tablet
