### ISSUE TITLE
Notifications: New order notifications always open the detail for the most recent order

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2832] opened 2020-09-09 17:18 UTC
**Describe the bug**

As of version 4.6 we support multiple new order notifications. However, no matter which notification I tap on, I’m taken to the order detail screen for the most recent order (not the order whose notification I tapped on).

**To Reproduce**

1. Generate 2 new order notifications from your store.
2. Verify that you are able to see both notifications in the notifications tray.
3. Tap each order notification.

Result: No matter which order notification you tap on, it opens the most recent order details.

**Expected behavior**

Tapping a new order notification should take you to the details for that order.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: Originally observed and reported in version 4.6 (internal ref: p5T066-1nX-p2#comment-5244); reproduced in 5.0-rc-1.

**Comment by designsimply** [comment] 2021-05-20 23:01
Tested and confirmed using WCAndroid 6.4-rc-1 on Pixel 3 Android 11 with the steps provided.

Note: I also found that if a past order is already open in the app and a new order notification comes in, tapping the push notification does not take you to the new order. @anitaa1990 should I file this as a separate issue or can it be handled as part of this one?

**Comment by anitaa1990** [comment] 2021-05-21 05:27
Thank you for the ping @designsimply! 

> I also found that if a past order is already open in the app and a new order notification comes in, tapping the push notification does not take you to the new order. @anitaa1990 should I file this as a separate issue or can it be handled as part of this one?

This is a [known issue](https://github.com/woocommerce/woocommerce-android/issues/3151#issuecomment-731153888) and it's been open for a while 😞 This requires a fix in the backend API and it's been on hold for a while now 😬

**Comment by designsimply** [comment] 2021-07-29 21:25
I re-tested this as part of 7.2 beta testing and confirmed the problem is still happening where if there are multiple push notifications then tapping on any of them results in only the latest one opening in the app.

Would it be a good time to try to update the API? Just checking!

Video: [2m3s](https://user-images.githubusercontent.com/1119271/127567771-300250ab-211e-468a-8e47-726f556076c1.mp4)
<sup>Tested with WCAndroid 7.2-rc-1 on Pixel 3 Android 11 site worthwhile-seahorse.jurassic.ninja running WordPress 5.8 Jetpack 9.9.1 WooCommerce 5.6.0-beta.1.</sup>

**Comment by anitaa1990** [comment] 2021-09-17 11:13
This should be fixed with the refactor to the notifications handling on android in #4655 so closing this for now.

**Closed as completed by anitaa1990** 2021-09-17 11:13 UTC
Labels: type: bug, feature: notifications
