### ISSUE TITLE
Orders: All Orders tab does not show new orders

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2219] opened 2020-04-08 11:53 UTC
**Describe the bug**

My "All Orders" tab is not updating at all. I see older orders (orders I received before updating to app version 4.0-rc-1) but no new orders.

I confirmed that new orders do appear on the Processing tab, but as soon as the order is fulfilled it disappears from that tab (as expected). I checked the All Orders tab before and after fulfilling the order, and it never appears on that tab.

I noticed this issue sounds similar to https://github.com/woocommerce/woocommerce-android/issues/1952, but it happens even though my store and my device are in the same timezone.

**To Reproduce**

1. Receive a new order on your store.
2. Open Orders > Processing tab and confirm the order appears there.
3. Open the All Orders tab and notice the order does not appear there.
4. Pull to refresh the screen and notice the order still does not appear there.

**Screenshots**

Processing|All Orders
-|-
![Screenshot_20200408-124136](https://user-images.githubusercontent.com/8658164/78780830-24a46e80-7997-11ea-8168-03b8d7daf1bc.png)|![Screenshot_20200408-123956](https://user-images.githubusercontent.com/8658164/78780838-2837f580-7997-11ea-952f-b6681bc0c762.png)

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.0-rc-1

Tested with WooCommerce plugin version 4.0.1 and 4.1.0-beta.1, with the same results.

**Comment by rachelmcr** [comment] 2020-04-08 12:19
Interestingly, these orders did load on the All Orders tab after I received a new review on my store.

**Comment by AmandaRiu** [comment] 2020-04-08 23:25
@rachelmcr I'm unable to reproduce this on my devices. What timezone are you in? Were you testing at 12:39am or pm? I'm just curious if this is a timezone issue. The **Processing** tab will show future-dated orders, but the **All** tab will not. This has been a point of headache for a while. The only thing that makes me think this isn't directly related to that is that if this order was marked as future-dated, it'd be showing up under a heading of "Upcoming" like this: 

<img src="https://user-images.githubusercontent.com/5810477/78842682-870c6780-79b5-11ea-8e96-83cd9e52ec62.jpg" width="330"/>

**Comment by AmandaRiu** [comment] 2020-04-08 23:26
@rachelmcr also, can you confirm this is not an issue on the previous version of the app? I'm just trying to narrow it down some. Thanks!

**Comment by AmandaRiu** [comment] 2020-04-09 01:00
NM: there is definitely something going on here with timezone translations. This is how it looks in the database:

<img width="594" alt="Screen Shot 2020-04-08 at 5 50 05 PM" src="https://user-images.githubusercontent.com/5810477/78846892-1b7cc700-79c2-11ea-8aed-02cf126f7530.png">

Which matches what we are getting back from the API:

<img width="975" alt="Screen Shot 2020-04-08 at 5 52 56 PM" src="https://user-images.githubusercontent.com/5810477/78846911-29cae300-79c2-11ea-83c6-3bf9ab720395.png">

But the translation is not working properly:

| Processing | All |
| -- | -- |
|<img width="328" alt="Screen Shot 2020-04-08 at 5 51 54 PM" src="https://user-images.githubusercontent.com/5810477/78846926-364f3b80-79c2-11ea-8b7c-6b26381c7c25.png">|<img width="329" alt="Screen Shot 2020-04-08 at 5 51 46 PM" src="https://user-images.githubusercontent.com/5810477/78846929-37806880-79c2-11ea-9c32-bf5ef9c11082.png">|

And the details:

| 2020-04-09T00:20:26Z | 2020-04-08T23:06:17Z | 2020-04-08T22:39:23Z |
| -- | -- | -- |
|<img width="329" alt="Screen Shot 2020-04-08 at 5 51 02 PM" src="https://user-images.githubusercontent.com/5810477/78846942-423afd80-79c2-11ea-8582-df2730fbbcba.png">|<img width="329" alt="Screen Shot 2020-04-08 at 5 51 17 PM" src="https://user-images.githubusercontent.com/5810477/78846946-4535ee00-79c2-11ea-87ee-d007dbfba95c.png">|<img width="330" alt="Screen Shot 2020-04-08 at 5 51 33 PM" src="https://user-images.githubusercontent.com/5810477/78846950-46671b00-79c2-11ea-845b-3c7aff0b5cf1.png">|

Something must've changed recently with how we are figuring out dates.

**Comment by AmandaRiu** [comment] 2020-05-13 18:39
This was fixed in #2226

**Closed by AmandaRiu** 2020-05-13 18:39 UTC
Labels: Order List, [Type] Bug
