### ISSUE TITLE
Product pictures won't load when adding new products

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#3152] opened 2020-11-11 10:29 UTC
It seems that in the latest beta version of the app, Product pictures won't load when adding new products. We received a [review](https://a8c.slack.com/archives/C013AAPA4G0/p1605031749062100) about it.
This should be investigated further.

**Comment by nbradbury** [comment] 2020-11-17 19:32
I'm not able to reproduce this. When I start a new product and add photos, they load just fine.

![Screenshot_20201117_143206](https://user-images.githubusercontent.com/3903757/99438408-c30b9180-28e1-11eb-8634-259b1653682d.png)

**Comment by shiki** [comment] 2021-03-03 22:41
Let's close this for now until we get more information from our customers.

**Closed as completed by shiki** 2021-03-03 22:41 UTC
Labels: type: bug, feature: product details
