### ISSUE TITLE
Fragment already added: NotifsListFragment

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#1005] opened 2019-04-18 17:40 UTC
From Fabric:

```
Caused by java.lang.IllegalStateException: Fragment already added: NotifsListFragment{1156718 #3 id=0x7f0a007f NotifsListFragment}
       at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManagerImpl.java:1916)
       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:765)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2625)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:2411)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:2366)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:2273)
       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:391)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:624)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1339)
       at android.app.Activity.performStart(Activity.java:7403)
       at android.app.Activity.performRestart(Activity.java:7477)
       at android.app.Activity.performResume(Activity.java:7482)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4256)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4328)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**In the last 90 days:**

**User Affected:** `1`
**Number of Crashes:** `1`
**Source:** `5cb75754f8b88c2963669482-fabric`
**Oldest Version Affected:** `1.6-rc-2`
**Device Rooted?** No
**Source:** `5cb75754f8b88c2963669482-fabric`

**Comment by nbradbury** [comment] 2019-04-19 16:55
Notes to myself: crash occurred when main activity was resumed after user tapped a new order push notification. The crash logs don't show any of our code that adds fragments, so I'm assuming the crash was caused by Android restoring the fragments when the activity was resumed.

**Comment by anitaa1990** [comment] 2019-04-26 09:14
@AmandaRiu @nbradbury I spent some time trying to reproduce this issue, to no avail. Tried to send notifications for new orders/new product reviews when app is in background but still in notification page. 

Realised Nick was working on this as well and this is somewhat of a mystery. Wondering if this can be put in the back burner for now? And revisit/debug if issue persists?

**Comment by nbradbury** [comment] 2019-04-26 10:12
@anitaa1990 I'm totally fine with putting crashes like this on the backburner, as long as we look into them first and don't find an obvious cause.

**Comment by nbradbury** [comment] 2019-12-12 14:06
Dupe of #1504

**Closed by nbradbury** 2019-12-12 14:06 UTC
Labels: Mystery Meat, [Type] Crash
