### ISSUE TITLE
Orders Badge Count does not show

### ISSUE THREAD

**Issue by minitaq** [woocommerce/woocommerce-android#5411] opened 2021-11-30 08:21 UTC
Orders Badge Count does not show in the android app.

However, when rotating the screen, then it shows the badge count.

[minitaq](https://minitaq.com)

**Comment by hichamboushaba** [comment] 2022-01-14 11:27
@minitaq can you please give more details about the bug? what's the version of the app on your device?

We are tracking a related issue #5069, but the steps to reproduce it are different than what you described.

**Comment by anitaa1990** [comment] 2022-03-24 07:26
This could be fixed in #5069 . @minitaq can you confirm please?

**Comment by hichamboushaba** [comment] 2023-08-25 15:11
Closing as the cause was fixed in the above PR.

**Closed as completed by hichamboushaba** 2023-08-25 15:11 UTC
Labels: type: bug, feature: order list
