### ISSUE TITLE
[Order Creation] The Shipping Address state initially navigates to countries

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#5816] opened 2022-02-07 22:36 UTC
## Steps to Reproduce

1. Tap Add Customer
2. Toggle the "Add a different shipping address“ to on.
3. Navigate to the State below.
4. Tap on the State. 
5. Notice that the country list is shown. 

https://user-images.githubusercontent.com/198826/152884089-61b02e0a-7bc2-4878-a6c7-df98ccc4099c.mp4

**Comment by nbradbury** [comment] 2022-03-16 18:34
Just an FYI that this isn't specific to order creation - it happens with shipping labels, too. https://github.com/woocommerce/woocommerce-android/issues/5074

**Comment by nbradbury** [comment] 2022-03-16 19:41
@hichamboushaba I've been looking into this but I might need your assistance. I do see that [statesAvailableFor()](https://github.com/woocommerce/woocommerce-android/blob/4cef8c04cccf8aa90acf35ba8828284df2b5806b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/AddressViewModel.kt#L38) returns the list of countries when the country code is an empty string, which in this case is why the state spinner shows a list of countries. However, I also see that the billing address state is disabled until a country is selected, but the same isn't true for shipping address state. Any chance you can take a quick look at why this is the case?

**Comment by hichamboushaba** [comment] 2022-03-17 08:55
@nbradbury I would love to help, I'll try to take a look during the day, but I'm not sure it'll help much since I'm not very familiar with this part of the code, maybe @wzieba would be of more help here.

**Comment by nbradbury** [comment] 2022-03-17 09:00
@hichamboushaba I assumed you would be best to ping because the same problem happens in the shipping labels feature, but looking at git history I see that @wzieba was more involved in this area. Sorry for the false ping!

**Comment by hichamboushaba** [comment] 2022-03-17 09:14
No worries at all @nbradbury, I'll try to take a look during the day, and if I figure something else, I'll share it 🙂 

> the same problem happens in the shipping labels feature

I assume you mean this [issue](https://github.com/woocommerce/woocommerce-android/issues/4387), I think this was fixed as a side-effect of the refactoring I did to the ViewModel there, but as we couldn't reproduce it, we didn't find the root cause back then.

**Comment by nbradbury** [comment] 2022-04-12 14:45
Closing, dupe of #5074

**Closed as completed** 2022-05-13 17:17 UTC
Labels: type: bug, feature: order creation
