### ISSUE TITLE
Crash in android.widget.TextView.onProvideAutoStructureForAssistOrAutofill

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#919] opened 2019-03-19 17:40 UTC
From Fabric:

```
Fatal Exception: java.lang.StringIndexOutOfBoundsException: length=22; index=23
       at java.lang.String.substring(String.java:2032)
       at java.lang.String.subSequence(String.java:2079)
       at android.widget.TextView.onProvideAutoStructureForAssistOrAutofill(TextView.java:11018)
       at android.widget.TextView.onProvideStructure(TextView.java:10921)
       at android.view.View.dispatchProvideStructureForAssistOrAutofill(View.java:8711)
       at android.view.View.dispatchProvideStructure(View.java:8659)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:519)
       at android.app.assist.AssistStructure.<init>(AssistStructure.java:2047)
       at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3654)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2077)
       at android.os.Handler.dispatchMessage(Handler.java:109)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:7470)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

**Users Affected:** 1
**First Seen In** `1.0.1`
**Source:** 5c8bf308f8b88c29633d0a6b-fabric

**Comment by aLT22** [comment] 2019-04-03 08:15
@jkmassel hello! I've faced with the same crash. Please, could you tell me, did you resolve this type of crash or not?

**Comment by AmandaRiu** [comment] 2019-04-03 13:20
@aLT22 This ticket has not been investigated yet. We are still unsure what caused the crash and so far it has happened only once to a single user so it will likely take some time to reproduce.

**Comment by aLT22** [comment] 2019-04-03 14:10
@AmandaRiu ye, I have the same (one user only on Android 9) and I have no idea what I should do with it. Thank you for response!

**Comment by jkmassel** [comment] 2019-04-03 14:30
It's also Android 9 for us – the user is on a Huawei device,  if that helps. We'll update this issue if we resolve it, but let us know if you make any progress as well? 😄

**Comment by aLT22** [comment] 2019-04-03 14:42
@jkmassel of course I will. Yep, Android 9 Huawei, absolutely the same issue.

**Comment by anitaa1990** [comment] 2019-04-25 06:36
I wasn't able to make much progress with this crash. It seems to be happening when we are trying to substring a text but there is only one place in the app where substring is being used: [here](https://github.com/woocommerce/woocommerce-android/blob/develop/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotificationHelper.kt#L34)

There are a couple of SO answers for android 8 devices facing crashes because of `importantForAutofill ` option. But nothing for android 9. And I was able to test in android 9 as well without facing any issues.

@aLT22 could you let us know exactly where in the app you are facing this crash? That would help us narrow it down and debug.

**Comment by aLT22** [comment] 2019-04-30 15:45
Hello @anitaa1990! I don't know exactly where did the crash happen. We faced with him through the Crashlitics and only one thing that we have is stacktrace with undefined line of code in the exact application. Just stacktrace from sdk. So we decided to skip the issue and focused on other features and bugs that have more priority for us.

**Comment by sunnylovejordan** [comment] 2019-08-02 08:11
Have some class extends TextView? Check class if invoke super.setText() in Override setText().

**Comment by nbradbury** [comment] 2019-12-12 14:08
Dupe of #1509

**Closed by nbradbury** 2019-12-12 14:08 UTC
Labels: Mystery Meat, [Type] Crash

**Comment by Odysseuszp** [comment] 2020-02-18 07:17
I had the same problem. On an Android 9 device. How to solve this problem?

**Comment by aLT22** [comment] 2020-02-18 11:36
@jkmassel @Odysseuszp I guess that it can be fixed by adding disabling option for `autofill`. Here you can find the solution: https://github.com/myksb1223/notes/blob/master/Android%208.0%20TextView%20'importantForAutofill'%20option.md

Spoiler: try to add `android:importantForAutofill="noExcludeDescendants"` to your `TextView` or its descendand

**Comment by varnithkumar** [comment] 2025-03-12 06:29
> [@jkmassel](https://github.com/jkmassel) [@Odysseuszp](https://github.com/Odysseuszp) I guess that it can be fixed by adding disabling option for `autofill`. Here you can find the solution: https://github.com/myksb1223/notes/blob/master/Android%208.0%20TextView%20'importantForAutofill'%20option.md
> 
> Spoiler: try to add `android:importantForAutofill="noExcludeDescendants"` to your `TextView` or its descendands


YES this code is working

**Comment by varnithkumar** [comment] 2025-03-12 06:30
try to add `android:importantForAutofill="noExcludeDescendants"` to your `TextView` or its descendands
