### ISSUE TITLE
UI broken when loading products after login

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#4084] opened 2021-05-25 20:01 UTC
**Describe the bug**
When I log into the app and switch tabs to "Products" the UI seems broken
- "no products yet" illustration is shown even though the fetch hasn't finished yet
- ~"new features available" label is shown in the middle of a screen~ (fixed in https://github.com/woocommerce/woocommerce-android/pull/4080)

**To Reproduce**
1. Clear apps data
2. Log in
3. Switch to "Products" tab
4. Notice the UI is broken before the data get loaded (you might need to manually slow down your internet connection to see the issue)

**Screenshots**
<img src="https://user-images.githubusercontent.com/2261188/119560565-b3c24080-bd69-11eb-9428-d44ac8d5447e.png" width="150px" />

**Expected behavior**
I'd expect to see the loading shimmer effect and when the load finishes see either "no products found" or "list of products"

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Emulator 
- Android version: android 30
- WooCommerce Android version: `develop` as of 5/25/21

**Comment by nbradbury** [comment] 2021-05-25 20:10
@malinajirka This is a partial dupe of #3549 which is fixed in #4080

**Comment by nbradbury** [comment] 2021-05-26 16:00
Related to this, the empty view isn't correctly centered, which is especially noticeable in landscape.

![portrait](https://user-images.githubusercontent.com/3903757/119693029-e75ca380-be19-11eb-872b-c77a8907aa39.png)

![landscape](https://user-images.githubusercontent.com/3903757/119693042-eaf02a80-be19-11eb-9fd0-c844ac7876bc.png)

**Closed as completed** 2021-05-27 07:04 UTC
Labels: type: bug, feature: product list
