### ISSUE TITLE
Dashboard: Top Performers only updates on pull to refresh or app restart

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#3140] opened 2020-11-06 17:02 UTC
**Describe the bug**

Although the store stats section is regularly updated, the Top Performers section of the dashboard doesn't update along with the stats graph. This results in the Top Performers section being out of sync with the stats (showing old data).

The only way I can update the Top Performers section is to pull to refresh or force close and relaunch the app.

**To Reproduce**

1. Place the app in the background.
2. Create a new order on your store.
3. Open the app and navigate to the My store dashboard.
4. If the store stats Today tab doesn't reflect the latest order, navigate e.g. to the This Week tab and then back to Today. This should refresh the stats graph.
5. Scroll down to the Top Performers section and notice the products from the latest order are not reflected there. (If no other orders were made today, the section will be empty or possibly showing yesterday's data.)
6. Pull to refresh and notice the Top Performers section is now updated.

**Screenshots**

Stats (correct for Today)|Top Performers (incorrect, showing yesterday's data)
-|-
![Screenshot_20201106-164220](https://user-images.githubusercontent.com/8658164/98393731-9dfd6000-2051-11eb-95c3-d6b02e698df6.png)|![Screenshot_20201106-164223](https://user-images.githubusercontent.com/8658164/98393735-9e95f680-2051-11eb-8ad2-63d5e1aced86.png)

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.4-rc-1

**Comment by anitaa1990** [comment] 2022-03-14 08:25
This was fixed as part of the home screen updates project. I tested again with the steps mentioned and could not reproduce it. So will close this issue.

**Closed as completed by anitaa1990** 2022-03-14 08:25 UTC
Labels: type: bug, feature: stats, priority: high
