### ISSUE TITLE
In landscape, marking as paid with cash keeps user on collect payment screen

### ISSUE THREAD

**Issue by lmischner** [woocommerce/woocommerce-android#11661] opened 2024-06-04 18:59 UTC
**Describe the bug**
If a user tries to make an order as paid via cash while their device is in landscape mode, it appears that it's effectively completed behind the scenes, but the user appears to get stuck on the collect payment page.

**To Reproduce**
1. Create a new order and add product or custom amount
2. Tap Collect Payment
3. Rotate device so it's in landscape mode (without being in split screen)
4. Tap cash
5. Tap mark as paid
6. Note you're brought back to the Collect Payment screen

**Screenshots**
Video taken with the Android Cash Payment improvements changes, but I also could reproduce this without that project present:

https://github.com/woocommerce/woocommerce-android/assets/103850310/d07c9235-d982-4f64-b7da-a175078f449d

**Expected behavior**
User should be brought to order list

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active,
  or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 7
- Android version: 13
- WooCommerce Android version: 18.8

**Comment by dangermattic** [comment] 2024-06-04 18:59
Thanks for reporting! 👍

**Comment by backwardstruck** [comment] 2024-06-04 19:38
I tested and this also happens with the feature flag off so it looks like that's why it's also happening with my feature. Should still be fixed but I believe it was like this (broken) for some time. i.e. it also occurs in 18.8, 18.7

Were you testing on 18.8 or 18.9 @lmischner ? This feature should still be off for 18.8:
https://github.com/woocommerce/woocommerce-android/issues/11623

Hopefully that's the case!

**Comment by lmischner** [comment] 2024-06-04 20:10
Yes, sorry that wasn't explicit! I also saw this behavior on 18.8 so should not have been introduced with your new feature. (I just had the screen recording from testing the new feature)

**Comment by backwardstruck** [comment] 2024-06-04 20:31
Got it. Makes sense, thanks.

**Comment by AnirudhBhat** [comment] 2024-12-02 05:40
@lmischner I tried this on the latest `trunk` branch on Pixel 7 emulator and couldn't reproduce this issue. Please see the attached video below. Let me know if I'm missing any steps. Thanks!

https://github.com/user-attachments/assets/f667287f-e488-41b7-97d0-90bd9b34cb11

**Comment by lmischner** [comment] 2024-12-03 21:43
Agreed -- I just tried on the latest beta on my Pixel and also could not see the issue.

**Comment by AnirudhBhat** [comment] 2024-12-04 06:47
Closing since the issue is no longer reproducible on the latest `trunk` branch

**Closed as completed by AnirudhBhat** 2024-12-04 06:47 UTC
Labels: type: bug, feature: mobile payments, priority: medium
