### ISSUE TITLE
Home Screen – Big titles design update

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3836] opened 2021-04-13 13:42 UTC
Ref: p91TBi-4N4-p2#comment-3867

The big Titles in the Home screen does not work for longer store names. We want to update the screen to include the “My Store” big title + store name as subtitle by default. On scroll, we could display the scrolled title style and the tabs.

<img width="303" alt="Screenshot 2021-04-13 at 7 09 14 PM" src="https://user-images.githubusercontent.com/22608780/114562353-1107a400-9c8c-11eb-9220-748f21f1be9e.png">

**Comment by Garance91540** [comment] 2021-05-20 13:25
Current Home screen updates:
<img width="638" alt="Screen Shot 2021-05-20 at 3 24 25 PM" src="https://user-images.githubusercontent.com/28450084/118986315-8b100480-b97f-11eb-8783-e8f2f034ae82.png">

**Comment by nbradbury** [comment] 2021-05-28 18:06
I haven't assigned this to myself, but I did some experimentation [here](https://github.com/woocommerce/woocommerce-android/compare/nick/big-titles-update) which may help when this is tackled.

It's a bit hacky because `CollapsingToolbarLayout` doesn't support a subtitle, so you have to add a textView to the `CollapsingToolbarLayout` in order to fake it, and then only show it when the dashboard is active.

**Comment by nbradbury** [comment] 2021-06-09 19:39
Note: This is currently assigned as a trial project.

**Comment by JorgeMucientes** [comment] 2021-06-11 16:11
Hello 👋🏼   @Garance91540 I'm Jorge, current trialmattician assigned to this task.  I have a couple doubts regarding the design and expected behavior: 
* Text size and color for the subtitle. I see in the project we have several textstyles defined: Headline1,  Subtitle1, Body1, etc So maybe you can point me directly which want to use. 
* Margin/paddings between title and subtitle
* What effect do you prefer to apply to make the subtitle invisible. I'm guessing fading in/out when scrolling? 

Thanks in advance!

**Comment by JorgeMucientes** [comment] 2021-06-12 07:55
Hi again Garance91540 😃  Just posting this so you can take a look next Monday. I was playing around a little bit with the visuals and wanted to check with you if this effect for the **subtitle** is fine for the task. Keep in mind this is work in progress and text appearance and margins are not final. 

https://user-images.githubusercontent.com/2663464/121772747-b8fbf980-cb77-11eb-9504-47e3075f6214.mp4

**Comment by JorgeMucientes** [comment] 2021-06-13 11:34
Hi again!! I'm sorry for bothering over the weekend 😞 . Hope you don't get to much notifications due to this and you don't see anything until Monday

I have more doubts regarding the behavior of the tabs showing/hiding when scrolling on My Store tab. I been doing some tests and here are the first results: 


https://user-images.githubusercontent.com/2663464/121805434-92a78e00-cc4b-11eb-9d1e-4c0ddfb950bf.mp4



As you can see in this first example feels like to many elements moving in the screen at once. It also feels kind of "janky" as transitions don't seem smooth. 
After some more playing around, a couple tweaks here and there, I think I have a "smoother" solution that seems ok. Although, still feels kind too much things moving around, specially when the tabs appear "sliding top down" in counter intuitive because it goes against the scrolling motion. 


https://user-images.githubusercontent.com/2663464/121805437-9804d880-cc4b-11eb-9147-91bc93dfc777.mp4

Let me know your thoughts on this and what did you have in mind for the tabs behavior. 

PS: Forget about the fact that tabs are showing when they shouldn't as there is no data available in my WooCommerce test account to display the chats. I'm just forcing the tabs to showcase the UI behavior.

**Comment by Garance91540** [comment] 2021-06-14 15:44
Hi there! 

All the content below the tabs should always be displayed. So the date should be displayed under the tabs on scroll. Is it possible to make that change?

**Comment by JorgeMucientes** [comment] 2021-06-14 18:13
Hi! 
hmm, it really does depend on whether you want the date to be part of the scrolling content or not. If we want the date to scroll (as it was implemented before adding any of these new changes) then it will scroll behind the tabs inevitably. Take the last video for example. Check at second 4. The date is already hidden behind the toolbar even before the tabs are shown. Right after that the tabs are shown and notice how when the tabs appear they don't overlay the currently displayed content, they move it down. 

Let me showcase a couple examples of what I'm trying to explain: 

If we have a big screen where there is almost no scroll possible then the date will be visible below the tabs

https://user-images.githubusercontent.com/2663464/121953232-97f4fd80-cd5d-11eb-8abc-d0e3bce4c79a.mp4

If on the other hand, we rotate the device. We will have much more scrolling content, so inevitably if we make a big swipe the date will scroll behind the tabs: 


https://user-images.githubusercontent.com/2663464/121953421-d4c0f480-cd5d-11eb-8ef7-d49a9978a83d.mp4

**Comment by Garance91540** [comment] 2021-06-15 15:57
Hi! Let's keep the date sticky under the top nav even on scroll for portrait mode and scrolled behind the tabs on landscape if possible to save real estate.

**Comment by JorgeMucientes** [comment] 2021-06-15 19:52
Hi! Thanks for taking a look on the matter 😃  . I agree with you, I think making the date sticky makes sense as it is an important data that we are currently hiding to fast under the top nav. I'll give it a go to your approach and let you know when I have something working.

**Comment by JorgeMucientes** [comment] 2021-06-17 07:51
Hi!! I have a first version of the sticky date on portrait and scrollable on landscape. Let me know your thoughts on this. 


https://user-images.githubusercontent.com/2663464/122354557-63e22e00-cf51-11eb-9eca-523a39595848.mp4

**Comment by nbradbury** [comment] 2021-06-17 10:49
> I have a first version of the sticky date on portrait and scrollable on landscape. Let me know your thoughts on this.

I think that looks great!

@Garance91540 Now that I see the tabs being hidden, I'm not sure I like it. I know the tabs take up a lot of real estate, but they're pretty important, and having them animate in and out is distracting. WDYT?

@JorgeMucientes The above comment has nothing to do with your implementation - you did it perfectly - it's just that now that I see it, I'm not sure we should do it.

**Comment by Garance91540** [comment] 2021-06-17 16:04
> @Garance91540 Now that I see the tabs being hidden, I'm not sure I like it. I know the tabs take up a lot of real estate, but they're pretty important, and having them animate in and out is distracting. WDYT?

I see what you are saying, but I think it will be really busy to have "My Store" + store name + tabs. @JorgeMucientes could you show us how that would look if we kept the tabs sticky?

**Comment by JorgeMucientes** [comment] 2021-06-17 19:44
Sure, no prob!

https://user-images.githubusercontent.com/2663464/122461054-26ae8800-cfb3-11eb-9b49-bec8c36b4f64.mp4

in dark mode

https://user-images.githubusercontent.com/2663464/122461122-3b8b1b80-cfb3-11eb-95cd-7b937f181add.mp4

And with scrolling date in portrait like we had before.

https://user-images.githubusercontent.com/2663464/122461438-a4729380-cfb3-11eb-97cf-d48ac7a17305.mp4

IMHO, tabs always visible feel better. The scrolling feels more natural and less elements moving around. I would keep the date sticky though, it's content that along with the tabs has a direct impact on the rest of the data displayed. But that's just an opinion of a total design noob 😆 

Let me know what you think and I will apply the needed changes.

**Comment by nbradbury** [comment] 2021-06-18 10:47
> IMHO, tabs always visible feel better. The scrolling feels more natural and less elements moving around.

I agree.

**Comment by Garance91540** [comment] 2021-06-18 13:42
Yeah it's a bit busy but I don't see another alternative for all our constraints so let's do this!

**Comment by nbradbury** [comment] 2021-06-18 17:31
@JorgeMucientes Congrats on taking this out of draft! I'll start my review shortly.

**Closed as completed** 2021-06-22 18:56 UTC
Labels: type: task, feature: stats
