### ISSUE TITLE
Orders: Shipment tracking never appears in order details

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#3350] opened 2020-12-18 14:31 UTC
**Describe the bug**

When a store has the Shipment Tracking extension, I expect to see a tracking option in the order details on orders that include physical products. Tracking should be hidden on orders that only have virtual products.

However, I don't see the option to add tracking on **any** orders, including orders with only physical products or orders with a mix of physical and virtual products.

**To Reproduce**
1. Install and activate the Shipment Tracking extension on your store.
2. Create an order on your store with physical products.
3. Open the order in the app and notice no tracking section appears.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.7-rc-1 (this is a new regression; it works as expected in 5.6.1)

**Comment by hichamboushaba** [comment] 2020-12-18 15:50
The cause of this issue is this [commit](https://github.com/woocommerce/woocommerce-android/pull/3330/commits/5326912102f94027d279e09088484f1b926e038d#diff-94e93aee231a2ada8044595882f7b660bfa18462cd7f34aa99e6f6230931a434R434), as we are hiding the section if the list is empty.

Also, in the same line I see another change of behavior, if the order has shipping labels we hide the tracking section, I don't think this was done before.

cc @0nko as you worked on the [PR](https://github.com/woocommerce/woocommerce-android/pull/3330), and @anitaa1990 as Ondrej is AFK, if you have more insight.

**Comment by 0nko** [comment] 2021-01-06 12:58
>  Also, in the same line I see another change of behavior, if the order has shipping labels we hide the tracking section, I don't think this was done before.

@hichamboushaba This was already present: https://github.com/woocommerce/woocommerce-android/pull/3330/files#diff-94e93aee231a2ada8044595882f7b660bfa18462cd7f34aa99e6f6230931a434L480

**Comment by anitaa1990** [comment] 2021-01-08 05:30
Closed via #3400

**Closed as completed by anitaa1990** 2021-01-08 05:30 UTC
Labels: type: bug, feature: order details
