### ISSUE TITLE
Order Number is briefly shown as null when opening a push notification

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#1939] opened 2020-02-13 16:02 UTC
**Describe the bug**

When opening a "New Order" push notification, the app will open and load the Order Details. The header briefly shows up as "Order #null". When the app is opened, there's also a short glimpse of the order details that immediately disappears.

~I couldn't take a screenshot because it happens too fast.~ Please see this [video (22s)](https://drive.google.com/file/d/136qDrm_sr_tzqJpjPms43_7RAcCWlP9S/view?usp=sharing). 

<img src="https://user-images.githubusercontent.com/198826/74452897-e8450e00-4e3e-11ea-8796-044e0ffa330a.png" width="320">

**To Reproduce**

1. Use a slow internet connection. 
1. Create an order from the website. 
2. Wait for the push notification and tap it. 

**Expected behavior**

I expected a placeholder without the technical "null" message.

**Isolating the problem (mark completed items with an [x]):**

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**

- Device: Google Pixel 3
- Android version: 10
- WooCommerce Android version: 3.6-rc-1

**Comment by SiobhyB** [comment] 2020-04-19 12:48
@shiki, are you still able to replicate this?

I tested using the same device as you (Pixel 3 running on Android 10) and the latest release of the WooCommerce app (version 4.0-rc-2). The order number always displayed correctly in my testing, with no flash of "null".

I wonder if it's been fixed somewhere along the line or if there's perhaps some other secret to replicating.

**Comment by shiki** [comment] 2020-04-22 21:05
Hi, @SiobhyB! Thanks for checking. 

I tried it again with the recent `develop` version (72c809531 / 4.2) and I can still reproduce it. It looks like it happens on a slow internet connection. 

I was able to take a [video (22s)](https://drive.google.com/file/d/136qDrm_sr_tzqJpjPms43_7RAcCWlP9S/view?usp=sharing) this time. On that video, you can see the title showing up as “Order #null”. There's also a short glimpse of the order details at the beginning that immediately disappears.

**Comment by SiobhyB** [comment] 2020-04-24 17:00
@shiki, thank you for the extra testing and details! I'm going to assign this to myself and try to tackle this weekend. :D (It'll be my first attempt at trying to contribute to the app's code, so any tips or suggestions welcome!)

**Comment by shiki** [comment] 2020-04-27 13:51
@SiobhyB Yay! 🎉Let us know if you have any questions. 🙂

**Comment by SiobhyB** [comment] 2020-05-04 09:07
@shiki, @AmandaRiu 👋

I wondered if either of you might be able to offer some thoughts on my initial notes, just in case I'm going down a completely wrong path. These are my initial notes:

# Delay in Order Details Loading

The delay in the order details loading, as well as the short glimpse of the details when first opening the notifications, seems like it may be beyond my capabilities. I also found some conversation in Slack (p1587397850214300-slack-mobile-support) that indicates that this is a wider issue. I'm leaning towards creating a separate GH issue for that specific part of the puzzle.

# Null in Title

I looked at the way the title is set in **ProductDetailFragment.kt** and can see that `productName` is initially assigned an empty string. I assume we can follow the same pattern for **OrderDetailFragment.kt** and prevent "null" from displaying in the action bar with the following steps:

* Initialize `orderNumber` with an empty string: `private var orderNumber = ""`
* Reference `orderNumber` instead of `presenter.orderModel?.number` in `getFragmentTitle()`.
* In `showOrderDetail()`, add `orderNumber = order.number;` just before the call to `updateActivityTitle()`. 
* Replace other instances of `order.number` with `orderNumber`.

After falling down a bit of a rabbit hole when researching this, I'm not confident if the above is the best approach. I'd really appreciate a gut check here or any hints you may have on better approaching the problem. 🙇

# Testing Push Notifications 

The reason I haven't created a pull request with those changes is that I'm not receiving push notifications when running the code in an emulator on Android Studio, which means I haven't been able to properly test this. 

I can confirm that notifications are enabled in the settings and I'm receiving them on the live version of the app. 

Is this a known issue? If not and notifications generally work in testing, I'm happy to try to figure out what the problem is with my specific setup, but thought I'd check first!

Thanks in advance!

**Comment by shiki** [comment] 2020-05-06 16:11
@SiobhyB Nice sleuthing! 

> Delay in Order Details Loading

We probably don't need to take care of this. From what I observed, the orders are refreshed in the background whenever the app receives a push notification. @AmandaRiu could probably confirm this. 

This particular issue seems to happen only if that background refresh fails for some reason.

> Null in Title

Thanks for directing us to where the issue is. My suggestion would be to fix the issue right _inside_ the `getFragmentTitle()` method. Based on its current implementation:

https://github.com/woocommerce/woocommerce-android/blob/298724cba992a82cbc22f56df9c66c823a90bfd1/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt#L193

If the order was not fetched before this is called, then that `presenter.orderModel` would be `null` and so that `getString()` call would look like this: 

```kotlin
getString(R.string.orderdetail_orderstatus_ordernum, null)
```

That's most probably why we're getting `"Order #null"`. This can probably be solved by making sure we're not passing a `null` value in `getString()`. Maybe using [`orEmpty`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/or-empty.html) would suffice:

```kotlin
getString(R.string.orderdetail_orderstatus_ordernum, presenter.orderModel?.number.orEmpty())
```

The result would probably be a `"Order #"` title. 

I'm not sure if `“Order #“` would be the best title in this case though. 😅 Maybe? 🤷 

> Testing Push Notifications

I'm using a Pixel 3 API 28 Emulator (with Google Play Services) and I can receive push notifications. I'm not sure but I think the Google Play Services is key. When creating an emulator, make sure to select one that has this icon:

<img src="https://user-images.githubusercontent.com/198826/81200291-007d8280-8f81-11ea-8183-21bec06dbefc.png" width="320">

I did notice that push notifications are not received when I'm _not debugging_ the app from Android Studio. Weird. 🤔 

### Testing

I've found a more reliable way of testing this by modifying the code. 😄 

1. **Comment out** this line in `OrderDetailPresenter`
    https://github.com/woocommerce/woocommerce-android/blob/298724cba992a82cbc22f56df9c66c823a90bfd1/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt#L132

    This _emulates_ the scenario where the order does not exist in the database or the app failed to refresh the orders list in the background. 
2. Run/Debug the app
3. Place the app in the background by pressing the Android home button
4. Create an order on the web
5. Wait for the push notification. Sometimes it takes a few seconds. 
6. Tap on the push notification. 
7. Because of the commented code, the app will fetch the order from the API and you should see the `“Order #null”` title.

**Comment by SiobhyB** [comment] 2020-05-10 13:42
@shiki, thank you **so much** for being so generous with your time and teachings here. 🙇‍♀️ I've created a pull request with that change.

**Comment by AmandaRiu** [comment] 2020-05-12 20:30
Great job digging into this issue @SiobhyB! Just following up on some of the comments:

> The reason I haven't created a pull request with those changes is that I'm not receiving push notifications when running the code in an emulator on Android Studio, which means I haven't been able to properly test this.

@SiobhyB It sounds like your missing some important AS configurations. Have you gotten set up to sync and unencrypt the `.mobile-secrets` repo? If not, the instructions can be found in the fieldguide by searching for "Mobile Secrets". Once you're able to sync and decrypt that repo, you'd then want to copy various config files to AS. Ping me directly and I can help you there. I _believe_ that is all that is needed.

> We probably don't need to take care of this. From what I observed, the orders are refreshed in the background whenever the app receives a push notification. @AmandaRiu could probably confirm this.

This is correct @shiki!

**Closed** 2020-05-14 20:47 UTC
Labels: Notifications, Order Details, Priority: Low, [Type] Bug, good first issue
