### ISSUE TITLE
java.lang.IllegalStateException: Already resumed, but proposed with update

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3762] opened 2021-03-29 10:33 UTC
There are aa bunch of crashes with the same stacktrace but in different parts of the app, mostly related to products.

```
java.lang.IllegalStateException: Already resumed, but proposed with update true
    at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:335)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:330)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250)
    at com.woocommerce.android.ui.products.ProductShippingClassRepository.onProductShippingClassesChanged(ProductShippingClassRepository.kt:91)
```

```
java.lang.IllegalStateException: Already resumed, but proposed with update https://tmabazzar.in/wp-content/uploads/2021/03/dreamstime_l_5556861-1.jpg
    at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:335)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:330)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250)
    at com.woocommerce.android.media.MediaFilesRepository.onMediaUploaded(MediaFilesRepository.kt:74)
```

```
java.lang.IllegalStateException: Already resumed, but proposed with update SUCCESS
    at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:335)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:330)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250)
    at com.woocommerce.android.ui.orders.tracking.OrderShipmentProvidersRepository.onOrderShipmentProviderChanged(OrderShipmentProvidersRepository.kt:93)
```

```
java.lang.IllegalStateException: Already resumed, but proposed with update CompletedExceptionally[java.lang.Exception: BAD_REQUEST, cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received]
    at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:335)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:330)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250)
    at com.woocommerce.android.media.MediaFilesRepository.onMediaUploaded(MediaFilesRepository.kt:66)
```

**Comment by hichamboushaba** [comment] 2021-05-31 11:42
Re-opening this as it's [still occurring](https://sentry.io/organizations/a8c/issues/1079436016/events/af0c23bc06f34928b741d6903ae2ca27/?project=1459556&statsPeriod=14d) in 6.7.
The last crash concerns `onMediaUploaded` of `MediaFilesRepository`

**Comment by hichamboushaba** [comment] 2021-05-31 11:54
My mistake, it has the same stacktrace, but the cause is different:
```
NullPointerException
event.media.url must not be null
```
so I'll re-close this ticket.

**Closed as completed by hichamboushaba** 2021-05-31 11:54 UTC
Labels: feature: order details, type: crash, feature: product details
