### ISSUE TITLE
Product Detail: Total orders does not match wp-admin

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1741] opened 2019-12-19 04:52 UTC
**Describe the bug**
The **Total Orders** section on the Product Detail view in the app does not match the **items sold** or **orders** count for that product in from wp-admin. This is across all the products I checked on my test store. 

**Screenshots**
![app-orders-count](https://user-images.githubusercontent.com/5810477/71145945-8e2e2080-21e0-11ea-98c7-968e6888bed7.png)

![items_sold_wpadmin](https://user-images.githubusercontent.com/5810477/71145955-925a3e00-21e0-11ea-9535-c76d5b6a3eba.png)

cc: @nbradbury since he's most familiar with this code

**Comment by rachelmcr** [comment] 2020-01-15 17:54
I'm also seeing discrepancies here, even when I set the date range under Analytics > Products in wp-admin to span the entire time my store has been open.

I'm not sure if it's because of refunded/restocked items or perhaps because of orders that include multiple products, but the numbers for all of the products I've checked are off, too.

**Comment by rachelmcr** [comment] 2020-01-30 12:28
I confirmed the same issue exists in WooCommerce iOS and stems from the `total_sales` field in WooCommerce core not accurately reflecting product sales. This could possibly be related to https://github.com/woocommerce/woocommerce/issues/23796 and would either require a fix in core or a different approach to displaying total orders in the apps.

**Comment by rachelmcr** [comment] 2020-07-02 13:19
I'm closing this issue since total orders was removed from the product detail screen in https://github.com/woocommerce/woocommerce-android/pull/2152 (now released to all users).

**Closed by rachelmcr** 2020-07-02 13:19 UTC
Labels: Product Details, Server-side change needed, [Type] Bug
