### ISSUE TITLE
Notifications appear in English even if the device language is set to another language such as Spanish

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#4552] opened 2021-08-03 22:56 UTC
From an app review: 

> The app is very good ... It has some details to improve, for example in the Spanish version when it tells you that a new order has arrived, it appears in English. The rest very good.
> 
> <sup>Aug 3, 2021, 11:46 - 4-stars - WCAndroid 7.1 - Android 11</sup>

Tested and confirmed using the following steps:

1. On the device, set the device language to Spanish.
1. In the app, log in and switch to your test store then background the app.
1. On the web, submit a new order on the same site from the previous step.
1. Wait for the new order notification to appear and check to see if it appears in Spanish as expected.

**Result:** notifications appear in English even if the device language is set to another language such as Spanish.

<img src="https://user-images.githubusercontent.com/1119271/128096419-bc7389c1-e24a-457f-863e-568facea2c25.png" width="270" alt="notification-in-english-even-with-device-languate-set-to-spanish-wcandroid-7 2-rc-1">
<sup>Tested with WCAndroid 7.2-rc-1 on Pixel 3 Android 11 logged in as testuser011121 using site worthwhile-seahorse.jurassic.ninja running WordPress 5.8, Jetpack 10.0, WooCommerce 5.6.0-beta.1, WooCommerce Product Add-ons 4.1.0, WooCommerce Shipping & Tax 1.25.17.</sup>

**Comment by hichamboushaba** [comment] 2021-08-09 14:59
@designsimply the notification content is coming from the backend, and I think its language depends on the WordPress.com account's language, I think this is not a bug.

If you set a different language here https://wordpress.com/me/account, it will be used in the notification's text according to my tests.

cc @anitaa1990 as you have more knowledge about how notifications work.

**Comment by hichamboushaba** [comment] 2022-01-14 11:48
@anitaa1990 can you take a look at this please? 🙂
I think we can close it as it's not a bug.

**Comment by anitaa1990** [comment] 2022-03-24 08:23
> If you set a different language here https://wordpress.com/me/account, it will be used in the notification's text according to my tests.

Yup, I can confirm this is the case 😄

**Closed as completed by anitaa1990** 2022-03-24 08:23 UTC
Labels: type: bug, feature: notifications
