### ISSUE TITLE
Huge ripple on Logout

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#3116] opened 2020-10-30 11:49 UTC
The ripple background on Settings > Logout is way too big.

![PXL_20201030_114616827](https://user-images.githubusercontent.com/3903757/97701811-635d5b80-1a84-11eb-8af8-46c89a596c65.jpg)

**Comment by AmandaRiu** [comment] 2020-12-29 16:29
Duplicate of https://github.com/woocommerce/woocommerce-android/issues/3233. Closing.

**Closed as completed by AmandaRiu** 2020-12-29 16:29 UTC
Labels: type: bug, category: duplicate, good first issue
