### ISSUE TITLE
Crash when clicking on review notification

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1196] opened 2019-07-02 10:48 UTC
When testing this [PR](https://github.com/woocommerce/woocommerce-android/pull/1175), I got this crash when clicking on the notification for a product review.

```
2019-07-02 15:53:45.889 17416-17416/com.woocommerce.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woocommerce.android, PID: 17416
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.ui.main.MainActivity}: java.lang.IllegalStateException: Fragment NotifsListFragment{8b68b20 id=0x7f0a00a5 NotifsListFragment} does not have a NavController set
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Fragment NotifsListFragment{8b68b20 id=0x7f0a00a5 NotifsListFragment} does not have a NavController set
        at androidx.navigation.fragment.NavHostFragment.findNavController(NavHostFragment.java:119)
        at androidx.navigation.fragment.FragmentKt.findNavController(Fragment.kt:29)
        at com.woocommerce.android.ui.notifications.NotifsListFragment.openReviewDetail(NotifsListFragment.kt:319)
        at com.woocommerce.android.ui.main.MainActivity.showNotificationDetail(MainActivity.kt:557)
        at com.woocommerce.android.ui.main.MainActivity.initFragment(MainActivity.kt:514)
        at com.woocommerce.android.ui.main.MainActivity.onCreate(MainActivity.kt:137)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
```

### Steps to reproduce the crash:
- Enable `Do not keep activities`.
- Open the app login to a test site and close the app. Ensure that the app is cleared from the back stack.
- Write a product review from a test site.
- Once you receive a notification for the test site, click on it in the app.
- Notice that the app crashes.

**Comment by nbradbury** [comment] 2019-07-02 15:25
@anitaa1990 This **may** not be an issue. I've seen similar crashes after switching between branches that have navigation changes. Rebuilding the app fixes the problem.

**Comment by anitaa1990** [comment] 2019-07-03 02:25
Thanks @nbradbury! I didn't know that this was an existing issue. I tried the to clean and build the project again but got faced with the same issue. I tested this with the latest 2.2-rc-1 beta release version and getting the same crash. I did note that this only happens when `Do not keep activities` is enabled though. I'll update the issue description to include steps on how to reproduce this

**Comment by nbradbury** [comment] 2019-07-03 15:29
@anitaa1990 Hmm, I'm still not able to repro this, and I tried the 2.2-rc-1 beta release with "Don't keep activities" enabled.

**Comment by AmandaRiu** [comment] 2019-07-03 19:45
@nbradbury I was able to reproduce this issue on my emulator (Pixel 2 running API 28):
```
         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: com.woocommerce.android, PID: 6446
                         E  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.ui.main.MainActivity}: java.lang.IllegalStateException: Fragment NotifsListFr
                            agment{2e0cc3b id=0x7f0a00a5 NotifsListFragment} does not have a NavController set
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
                         E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
                         E      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                         E      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                         E      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
                         E      at android.os.Handler.dispatchMessage(Handler.java:106)
                         E      at android.os.Looper.loop(Looper.java:193)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6669)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                         E  Caused by: java.lang.IllegalStateException: Fragment NotifsListFragment{2e0cc3b id=0x7f0a00a5 NotifsListFragment} does not have a NavController set
                         E      at androidx.navigation.fragment.NavHostFragment.findNavController(NavHostFragment.java:119)
                         E      at androidx.navigation.fragment.FragmentKt.findNavController(Fragment.kt:29)
                         E      at com.woocommerce.android.ui.notifications.NotifsListFragment.openReviewDetail(NotifsListFragment.kt:319)
                         E      at com.woocommerce.android.ui.main.MainActivity.showNotificationDetail(MainActivity.kt:555)
                         E      at com.woocommerce.android.ui.main.MainActivity.initFragment(MainActivity.kt:514)
                         E      at com.woocommerce.android.ui.main.MainActivity.onCreate(MainActivity.kt:137)
                         E      at android.app.Activity.performCreate(Activity.java:7136)
                         E      at android.app.Activity.performCreate(Activity.java:7127)
                         E      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
                         E      ... 11 more
```

I followed these steps:
1. Download the [2.2-rc-1 beta release](https://github.com/woocommerce/woocommerce-android/releases/tag/2.2-rc-1)
2. Open emulator and uninstall WooCommerce. 
3. Drag and drop the apk downloaded in step 1 into the emulator to install. 
4. Log into the app with a test store (I used my testwooshop one which I'm pretty sure you have access to as well)
5. I didn't click on any of the tabs or anything in the app once logged in. Just minimized it and then force closed it from within the app overview.
6. Submit a review on my store and wait for the device to get the notification.
7. Click on the notification -- crash.

**Comment by nbradbury** [comment] 2019-07-03 20:48
@AmandaRiu Thanks, I was able to repro that now. It looks like we _may_ be trying to access the nav controller before the fragment has been attached, which would be a shame since we switched to the nav component to avoid that kind of thing. 

Anyway...I've assigned this to myself and will dig into it after July 4.

**Closed** 2019-07-08 03:03 UTC
Labels: [Type] Crash
