### ISSUE TITLE
Notifications: push notification does not open the correct order if the app already has another order open when the notification is tapped

### ISSUE THREAD

**Issue by reginabally** [woocommerce/woocommerce-android#3151] opened 2020-11-11 02:42 UTC
**Describe the bug**

Originally reported in 3479113-zen.

> I have noticed a bug where if I open a new order by tapping a notification everything is fine. But if I open another new order from a notification, in the notes section of the new order it shows notes from previous orders as well as the notes for the current order. If I exit to the list of orders and go back into the order it correctly only displays the notes for that order.

**To Reproduce**
1. Create an order on a WooCommerce site.
2. App received the notification. Don't view the order yet.
3. Create another order on the site with different products and customer note.
4. App received another notification.
5. Tap on one of the new order notifications to view the order details.
6. Pull down the notification bar and tap on another new order notification.
7. Notice the same order details show up in the app.

**Screenshots**

Screen recording: https://d.pr/v/idMMzs/1vryvIlgxs

**Expected behavior**

I would expect the order details in the app to show the correct details of the order when I tapped on the respective new order notifications.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Mobile Environment**

Reported in 3479113-zen on app version 5.3.

I'm able to replicate this on:
- Device: OPPO Reno 4
- Android version: Android 10
- WooCommerce Android version: 5.4-rc-1

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://woo20200908.mystagingwebsite.com
Site address (URL): https://woo20200908.mystagingwebsite.com
WC Version: 4.6.2
REST API Version: ✔ 4.6.2
WC Blocks Version: ✔ 3.4.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.2
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.24
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.73.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.24-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.6.2
WC Database Prefix: wp_
Total Database Size: 5.97MB
Database Data Size: 4.06MB
Database Index Size: 1.91MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.47MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 0.42MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 53
page: 6
post: 2
product: 27
product_variation: 20
shop_order: 12

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Jetpack by WordPress.com: by Automattic – 9.1
WooCommerce: by Automattic – 4.6.2

### Inactive Plugins (5) ###

Akismet Anti-Spam: by Automattic – 4.1.7
All in One Product Quantity for WooCommerce: by WPWhale – 3.3 – Installed version not tested with active version of WooCommerce 4.6.2
Custom Order Status for WooCommerce: by Tyche Softwares – 1.4.11 – Installed version not tested with active version of WooCommerce 4.6.2
WooCommerce Shipment Tracking: by WooCommerce – 1.6.26 – Installed version not tested with active version of WooCommerce 4.6.2
Wordfence Security: by Wordfence – 7.4.12

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #104 - /shop/
Cart: #105 - /cart/
Checkout: #106 - /checkout/
My account: #107 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 25
Oldest: 2020-10-15 01:39:08 +0000
Newest: 2020-11-11 02:45:20 +0000

Pending: 1
Oldest: 2020-11-11 02:46:22 +0000
Newest: 2020-11-11 02:46:22 +0000

`
```
</details>

**Comment by AliSoftware** [comment] 2020-11-16 15:30
Seems this hasn't got a chance to get picked before today's 5.5 ❄️  code freeze, so pushing it further to milestone 5.6

**Comment by anitaa1990** [comment] 2020-11-20 12:55
It looks like this issue is because we are fetching the `NotificationModel` (which contains the `orderId`) from the local db based on the `notificationID` sent from the backend API. And all new order notifications have the same `notificationID`. So when clicking on an older new order notification, it still opens the latest order. 

For instance: 
- There are two new order notifications: **Notification1** and **Notification2**.
- User clicks on **Notification1** but it opens the order detail screen for **Notification2**. 

This is because **Notification2** replaces **Notification1** from the local db since they both contain the same `notificationID`.

I'm not sure if this is something we can fix in the app but might need to make a change in the backend. cc @astralbodies. 
I'm marking the issue as on hold for now.

**Comment by anitaa1990** [comment] 2020-11-20 12:56
I see in iOS if we click on one of the notifications, the entire notification list is removed from the notification tray so this issue happens only on Android.

**Comment by rezzap** [comment] 2020-12-04 11:06
Another report of this in 3540739-zen 

App: Woo Android 5.5

The user only replicated the issue when clicking on the notification. Screenshot included in the ticket.

**Comment by reginabally** [comment] 2021-01-04 02:36
Another report in 3613158-zen on Woo Android 5.6.3.

Screen recordings are included in the ticket.

**Comment by rachelmcr** [comment] 2021-05-11 11:54
Another report in 3977451-zen in Woo Android 6.6-rc-2.

Same as described in the original report (only an issue when opening order details from a push notification); screenshots in the ticket.

**Comment by designsimply** [comment] 2021-06-11 18:10
Tested and confirmed that if an order is already open, tapping on a push notification for another order will not open the newer order. In my testing, this doesn't happen unless the app had an open order details screen at the time the push notification was tapped.

Here are my testing steps: 

1. Open any order in the app.
1. Background the app, leaving the order details screen as the last open screen.
1. On the web, submit a new order.
1. On the device, tap the push notification for the new order.
1. Observe that the app opens to the order details screen that was left open before and not to the new one from the push notification.

<sup>Tested with WCAndroid 6.8-rc-2 on Pixel 3 Android 11.</sup>

**Comment by designsimply** [comment] 2021-06-11 18:13
@anitaa1990 (just checking) is there space to put this one back into the mix or should it still be on hold?

**Comment by designsimply** [comment] 2021-07-29 21:21
I re-tested this as part of 7.2 beta testing and confirmed that if an order is already open in the app then tapping a new push notification for a new order returns you to the order you had opened before instead of taking you to the new order. ([33s](https://user-images.githubusercontent.com/1119271/127567403-f547b652-9427-4d17-b5c6-bcc79601d56e.mp4))

<sup>Tested with WCAndroid 7.2-rc-1 on Pixel 3 Android 11 site worthwhile-seahorse.jurassic.ninja running WordPress 5.8 Jetpack 9.9.1 WooCommerce 5.6.0-beta.1.</sup>

**Comment by reginabally** [comment] 2021-09-14 02:35
Another report in 4295474-zd-woothemes on app version 7.4.

**Comment by astralbodies** [comment] 2021-09-14 19:31
@anitaa1990's doing some testing with push notifications this week, so I've asked if she might have time to look into this one again!

**Comment by anitaa1990** [comment] 2021-09-15 03:34
Hey @reginabally this is actually fixed as part of this refactor in #4635  and released in v7.5 (which is currently in beta). Can you ask the user to update to the latest beta version and test again?

**Comment by anitaa1990** [comment] 2021-09-15 03:35
I'll close this issue for now but do feel free to reopen it and ping me if this issue still persists in 7.5 😄

**Closed as completed by anitaa1990** 2021-09-15 03:35 UTC
Labels: type: bug, feature: order details, feature: notifications, priority: high, status: on hold

**Comment by reginabally** [comment] 2021-09-15 06:42
Thanks, @anitaa1990! I've informed the user and invited them to join our beta program to test it out.
