### ISSUE TITLE
Image upload problem with Google Drive

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#3508] opened 2021-01-30 14:43 UTC
There is a problem seeing the image loading placeholder for a 2nd image upload after the 1st image upload is discarded, but only when using Choose from device > Google Drive. It works normally when selecting an image with Choose from device > Photos app.

[Video](https://cloudup.com/cS6fzgZ9gHy)

**Comment by shiki** [comment] 2021-03-01 18:06
Oh, this looks like a duplicate of #3577. I'll close this one.

**Closed as completed by shiki** 2021-03-01 18:06 UTC
Labels: type: bug, feature: product details
