### ISSUE TITLE
Woo stats data requires admin role

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#245] opened 2018-06-22 11:28 UTC
I was testing login and noticed I had to be an admin to get access to the stats data. Any other role ~(including shop manager)~ (shop manager currently supported) resulted in “no data available” on the Dashboard. 

The response I got for the stats request is below:

`{"code":"woocommerce_unauthorized_access","message":"User is not allowed to access this site","data":{"status":400}}`

### TODO
This should either be corrected on the server side, or we should display a message on the Dashboard stating the user doesn't have the required role to access stats.

**Comment by aforcier** [comment] 2019-05-01 12:02
This is mostly remedied now with two server-side patches:

D24412 gave all Shop Managers access to the Store stats.
D27500 did the same but for plain WordPress.com stats (in our case this affects the 'visitors' stat).

Note that for visitors stats to be displayed as a Shop Manager, access has to be given from the Jetpack stats settings screen by visiting https://[yourwebsite]/wp-admin/admin.php?page=jetpack&configure=stats and enabling it (see https://github.com/woocommerce/woocommerce-ios/issues/823#issuecomment-480030540 for fuller instructions). Otherwise the request will fail silently and the visitors field will just show a question mark.

I'm not sure we should expand the roles that have access to these stats server-side, as any role other than Administrator or Shop Manager can't even access WooCommerce data in `wp-admin`. We could however show a warning, or even consider preventing other roles from using the app.

**Comment by AmandaRiu** [comment] 2019-05-20 22:57
Woo stats now available to Shop Managers. Closing ticket.

**Comment by aforcier** [comment] 2019-05-21 12:36
@AmandaRiu maybe this is captured somewhere else, but I thought I'd mention that we may still want to do this:

> we should display a message on the Dashboard stating the user doesn't have the required role to access stats.

for roles other than administrator and shop manager, as the experience is a little broken in those cases. However, we may consider preventing login or showing a static screen when logged in as non-admin/shop manager roles since most of the app is unusable to users with those roles.

**Comment by AmandaRiu** [comment] 2019-05-27 18:19
ah, that's a good point @aforcier  - I'll reopen this ticket.

**Comment by designsimply** [comment] 2021-04-15 01:45
Tested and confirmed that it is not possible to view visitor stats on the My Store screen in the app if you are logged as a user role that does not have stats viewing permissions on the Jetpack site. By default, only the Administrator role has rights to view Jetpack stats.

1. Go to Jetpack > Settings > Traffic. 
1. Scroll to "Site stats" and expand the section.
1. Toggle "Shop manager" on in the "Allow stats reports to be viewed by" section.

<img width="1440" alt="Screen Shot 2021-04-14 at Apr 14 7 16 57 PM" src="https://user-images.githubusercontent.com/1119271/114801817-b63c7e00-9d59-11eb-9441-2f8f677c0504.png">

Default Jetpack Site Stats Settings|After toggling "Shop manager" on <br>in "Allow stats reports to be viewed by"
---|---
<img src="https://user-images.githubusercontent.com/1119271/114801434-ecc5c900-9d58-11eb-9855-7d7ccbb898a9.png" width="270" alt="Screenshot_20210414-193400">|<img src="https://user-images.githubusercontent.com/1119271/114801432-ec2d3280-9d58-11eb-88fb-bdffb0448c75.png" width="270" alt="Screenshot_20210414-193514">

<sup>Tested with WCAndroid 6.4-rc-2 on Pixel 3 Android 11 on favourite-saki.jurassic.ninja (WP 5.7.1-RC1 JP 9.6.1 WC 5.2.1) logged in as testuser121620 (Shop Manager role).</sup>

If you have an Editor role, things are a bit worse and I filed a separate issue at https://github.com/woocommerce/woocommerce-android/issues/3846 for that case.

Regarding prioritization, I agree the case where viewing stats has not been turned on for some user roles in Jetpack is low priority but feel https://github.com/woocommerce/woocommerce-android/issues/3846 is high priority.

**Comment by joshbetz** [comment] 2021-09-17 19:49
I think the API portion of this has been resolved, but please correct me if I'm wrong.

**Comment by anitaa1990** [comment] 2022-03-04 08:30
We're currently only support Admin and Shop Manager role in the mobile apps so I'm closing this issue. We do have plans to support other user roles in the app in the future so this will be taken in account during the design phase.

**Closed by anitaa1990** 2022-03-04 08:30 UTC
Labels: type: bug, feature: stats
