### ISSUE TITLE
Infinite Loading on Products or Orders Screen for Empty Stores on Tablet Devices

### ISSUE THREAD

**Issue by jd-alexander** [woocommerce/woocommerce-android#11023] opened 2024-03-06 19:04 UTC
**Describe the bug**
When navigating to the orders or products functionality on a tablet device in a store with no orders and zero products, the skeleton view appears and persists indefinitely. This results in the screen entering an infinite loading state.

**To Reproduce**
1. Create a store with no orders and no products.
2. On a tablet device, navigate to the 'Orders' or 'Products' screen.
3. In the right pane, where order or product details should be displayed, observe that the skeleton view loads and continues to do so indefinitely.

**Expected behavior**
The expected behavior is for the skeleton view to eventually be replaced with a message indicating that there are no orders or products, rather than entering an infinite loading state. This would inform the user of the lack of data and prevent confusion or frustration due to the perpetual loading indicator.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Nexus 10 
- OS Version: Android 14
- WooCommerce Version: `trunk`

**Comment by dangermattic** [comment] 2024-03-06 19:04
Thanks for reporting! 👍

**Comment by malinajirka** [comment] 2024-03-07 11:54
This seems like a duplicate of https://github.com/woocommerce/woocommerce-android/issues/10881, @jd-alexander could you double check it and close this issue if it's a duplicate. Thanks!

**Comment by jd-alexander** [comment] 2024-03-07 14:54
You are right. I never saw it. Thanks for pointing it out.

**Closed as completed** 2024-03-07 14:54 UTC
Labels: type: bug, feature: order details, feature: product details, category: tablet
