### ISSUE TITLE
Crash due to race condition after WooCommerce is uninstalled from site

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#8250] opened 2023-01-25 11:03 UTC
**Describe the bug**
In version `11.9` an [old crash](https://sentry.io/organizations/a8c/issues/2155569010/events/21187f56d74b4dd3a1d9f10f22c7c7f2/?project=1459556) came back: 

```
java.lang.IllegalStateException: SelectedSite.get() was accessed before being initialized - siteId -1.
Consider calling selectedSite.exists() to ensure site exists prior to calling selectedSite.get().
    at com.woocommerce.android.tools.SelectedSite.get(SelectedSite.kt:51)
    at com.woocommerce.android.ui.mystore.data.StatsRepository$fetchRevenueStats$2.invokeSuspend(StatsRepository.kt:70)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
    at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
Looking at the logs for users that have experienced this crash we can see that it happen always after we check if WooCommerce plugin is installed for the site. `Selected site no longer has WooCommerce` is always logged before crashing. 

The possible reason for the crash is a race condition due to[ this new code](https://github.com/woocommerce/woocommerce-android/pull/8125/files#diff-382495f533cb26e13cb937a8bf65d7e96bc9d04fa582e8618ed0b25c9974c4d3) added in `11.9`. Basically, we are resetting the selected site while we are still fetching data for my store tab. Fetching this data requires a selected site and thus causing the crash. 

This crash is low priority as it’s a corner case. I don’t think many users will try to open the app using a site where they have uninstalled WooCommerce. Plus the race condition doesn’t happen often, I was unable to reproduce it.

**Comment by JorgeMucientes** [comment] 2023-01-26 11:44
Additional context: 

> Just to add a small remark, the experience the users are getting after the crash is not much different from what they would normally get even if the app didn’t crash, the next time they open the app it will show them the site picker, and from there they’ll know that their site doesn’t have Woo anymore, so as you said, it’s not urgent :slightly_smiling_face:.
As for the fix, unless I’m missing some scenarios, I think that since we have this [logic](https://github.com/woocommerce/woocommerce-android/blob/7f702870559791b8ee48edb4ce2407ad026dccac/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt#L51), the only cases where SelectedSite would throw the exception is if we intentionally resetted it, and this means we are aware that the site doesn’t exist anymore and we want to show the Login screen and the Site Picker. WDYT about attaching a default UncaughtExceptionHandler that catches the exception and either ignores it or restarts MainActivity? We need to check how this would impact Sentry’s crash reporting though.

**Comment by hichamboushaba** [comment] 2023-12-19 11:16
Closing as duplicate of https://github.com/woocommerce/woocommerce-android/issues/4114

Just to group all discussions on a single place.

**Closed as not planned by hichamboushaba** 2023-12-19 11:16 UTC
Labels: type: crash, priority: low
